# Tests for extractable first-stage model objects (Ticket S1)
# Verifies coefficients, VCV, RMSE against Stata `savefirst` CSV fixtures
# generated by generate-firststage-fixtures.do

# ============================================================================
# Fixture readers
# ============================================================================

read_fs_coef <- function(prefix) {
  fx <- read.csv(fixture_path(paste0(prefix, "_coef.csv")),
                 strip.white = TRUE)
  vals <- fx$estimate
  nms <- ifelse(fx$term == "_cons", "(Intercept)", fx$term)
  names(vals) <- nms
  vals
}

read_fs_vcov <- function(prefix) {
  read_vcov_fixture(fixture_path(paste0(prefix, "_vcov.csv")))
}

read_fs_scalars <- function(prefix) {
  fx <- read.csv(fixture_path(paste0(prefix, "_scalars.csv")),
                 strip.white = TRUE)
  out <- as.list(fx$value)
  names(out) <- fx$quantity
  out
}


# ============================================================================
# Tests: API and structure
# ============================================================================

test_that("first_stage() errors informatively without flag", {
  data(card, package = "ivreg2r")
  fit <- ivreg2(lwage ~ exper + expersq + black + south + smsa |
                  educ | nearc4 + nearc2, data = card)
  expect_error(first_stage(fit), "Re-fit with `first_stage = TRUE`")
})

test_that("first_stage() errors for OLS models", {
  data(card, package = "ivreg2r")
  fit_ols <- ivreg2(lwage ~ exper + expersq + black + south, data = card,
                     first_stage = TRUE)
  expect_error(first_stage(fit_ols), "Re-fit with `first_stage = TRUE`")
})

test_that("first_stage returns correct class and structure", {
  data(card, package = "ivreg2r")
  fit <- ivreg2(lwage ~ exper + expersq + black + south + smsa |
                  educ | nearc4 + nearc2, data = card, first_stage = TRUE)
  fs <- first_stage(fit)
  expect_type(fs, "list")
  expect_named(fs, "educ")
  expect_s3_class(fs$educ, "ivreg2_first_stage")

  expect_length(coef(fs$educ), 8L)
  expect_equal(dim(vcov(fs$educ)), c(8L, 8L))
  expect_length(residuals(fs$educ), 3010L)
  expect_length(fitted(fs$educ), 3010L)
  expect_equal(nobs(fs$educ), 3010L)
})


# ============================================================================
# Tests: Stata parity — coefficients, VCV, scalars
# ============================================================================

test_that("first_stage matches Stata (overidentified, IID)", {
  data(card, package = "ivreg2r")
  fit <- ivreg2(lwage ~ exper + expersq + black + south + smsa |
                  educ | nearc4 + nearc2, data = card, first_stage = TRUE)
  fs <- first_stage(fit)$educ

  stata_coef <- read_fs_coef("fs_overid_iid")
  stata_vcov <- read_fs_vcov("fs_overid_iid")
  stata_sc <- read_fs_scalars("fs_overid_iid")

  for (nm in names(stata_coef)) {
    expect_equal(coef(fs)[[nm]], stata_coef[[nm]], tolerance = stata_tol$coef,
                 label = paste0("coef [", nm, "]"))
  }
  expect_vcov_equal(vcov(fs), stata_vcov, tol = stata_tol$vcov)
  expect_equal(fs$sigma, stata_sc$rmse, tolerance = stata_tol$coef)
  expect_equal(fs$df.residual, as.integer(stata_sc$df_r))
})

test_that("first_stage matches Stata (overidentified, robust)", {
  data(card, package = "ivreg2r")
  fit <- ivreg2(lwage ~ exper + expersq + black + south + smsa |
                  educ | nearc4 + nearc2, data = card, vcov = "robust",
                  first_stage = TRUE)
  fs <- first_stage(fit)$educ

  stata_vcov <- read_fs_vcov("fs_overid_robust")
  stata_sc <- read_fs_scalars("fs_overid_robust")

  expect_vcov_equal(vcov(fs), stata_vcov, tol = stata_tol$vcov)
  expect_equal(fs$sigma, stata_sc$rmse, tolerance = stata_tol$coef)
  expect_equal(fs$df.residual, as.integer(stata_sc$df_r))
})

test_that("first_stage matches Stata (overidentified, cluster age M=11)", {
  data(card, package = "ivreg2r")
  fit <- ivreg2(lwage ~ exper + expersq + black + south + smsa |
                  educ | nearc4 + nearc2, data = card, clusters = ~age,
                  first_stage = TRUE)
  fs <- first_stage(fit)$educ

  stata_vcov <- read_fs_vcov("fs_overid_cluster")
  stata_sc <- read_fs_scalars("fs_overid_cluster")

  expect_vcov_equal(vcov(fs), stata_vcov, tol = stata_tol$vcov)
  expect_equal(fs$sigma, stata_sc$rmse, tolerance = stata_tol$coef)
  expect_equal(fs$df.residual, as.integer(stata_sc$df_r))
  expect_equal(fs$n_clusters, as.integer(stata_sc$N_clust))
})

test_that("first_stage matches Stata (just-identified, robust)", {
  data(card, package = "ivreg2r")
  fit <- ivreg2(lwage ~ exper + expersq + black + south + smsa |
                  educ | nearc4, data = card, vcov = "robust",
                  first_stage = TRUE)
  fs <- first_stage(fit)$educ

  stata_coef <- read_fs_coef("fs_just_robust")
  stata_vcov <- read_fs_vcov("fs_just_robust")
  stata_sc <- read_fs_scalars("fs_just_robust")

  for (nm in names(stata_coef)) {
    expect_equal(coef(fs)[[nm]], stata_coef[[nm]], tolerance = stata_tol$coef,
                 label = paste0("coef [", nm, "]"))
  }
  expect_vcov_equal(vcov(fs), stata_vcov, tol = stata_tol$vcov)
  expect_equal(fs$sigma, stata_sc$rmse, tolerance = stata_tol$coef)
})

test_that("first_stage matches Stata (weighted, IID)", {
  data(card, package = "ivreg2r")
  card$aw <- seq_len(nrow(card))
  fit <- ivreg2(lwage ~ exper + expersq + black + south + smsa |
                  educ | nearc4 + nearc2, data = card, weights = aw,
                  first_stage = TRUE)
  fs <- first_stage(fit)$educ

  stata_coef <- read_fs_coef("fs_overid_aw_iid")
  stata_vcov <- read_fs_vcov("fs_overid_aw_iid")
  stata_sc <- read_fs_scalars("fs_overid_aw_iid")

  for (nm in names(stata_coef)) {
    expect_equal(coef(fs)[[nm]], stata_coef[[nm]], tolerance = stata_tol$coef,
                 label = paste0("coef [", nm, "]"))
  }
  expect_vcov_equal(vcov(fs), stata_vcov, tol = stata_tol$vcov)
  expect_equal(fs$sigma, stata_sc$rmse, tolerance = stata_tol$coef)
})

test_that("first_stage matches Stata (weighted, robust)", {
  data(card, package = "ivreg2r")
  card$aw <- seq_len(nrow(card))
  fit <- ivreg2(lwage ~ exper + expersq + black + south + smsa |
                  educ | nearc4 + nearc2, data = card, weights = aw,
                  vcov = "robust", first_stage = TRUE)
  fs <- first_stage(fit)$educ

  stata_coef <- read_fs_coef("fs_overid_aw_robust")
  stata_vcov <- read_fs_vcov("fs_overid_aw_robust")
  stata_sc <- read_fs_scalars("fs_overid_aw_robust")

  for (nm in names(stata_coef)) {
    expect_equal(coef(fs)[[nm]], stata_coef[[nm]], tolerance = stata_tol$coef,
                 label = paste0("coef [", nm, "]"))
  }
  expect_vcov_equal(vcov(fs), stata_vcov, tol = stata_tol$vcov)
  expect_equal(fs$sigma, stata_sc$rmse, tolerance = stata_tol$coef)
})

test_that("LIML first-stage matches IID (same OLS first-stage)", {
  data(card, package = "ivreg2r")
  fit <- ivreg2(lwage ~ exper + expersq + black + south + smsa |
                  educ | nearc4 + nearc2, data = card, method = "liml",
                  first_stage = TRUE)
  fs <- first_stage(fit)$educ

  stata_coef <- read_fs_coef("fs_overid_liml")
  stata_vcov <- read_fs_vcov("fs_overid_liml")

  for (nm in names(stata_coef)) {
    expect_equal(coef(fs)[[nm]], stata_coef[[nm]], tolerance = stata_tol$coef,
                 label = paste0("LIML coef [", nm, "]"))
  }
  expect_vcov_equal(vcov(fs), stata_vcov, tol = stata_tol$vcov)
})


# ============================================================================
# Tests: broom methods
# ============================================================================

test_that("tidy() and glance() work for first-stage objects", {
  data(card, package = "ivreg2r")
  fit <- ivreg2(lwage ~ exper + expersq + black + south + smsa |
                  educ | nearc4 + nearc2, data = card, vcov = "robust",
                  first_stage = TRUE)
  fs <- first_stage(fit)$educ

  td <- tidy(fs)
  expect_s3_class(td, "tbl_df")
  expect_equal(nrow(td), 8L)
  expect_true(all(c("term", "estimate", "std.error", "statistic", "p.value",
                     "conf.low", "conf.high") %in% names(td)))

  gl <- glance(fs)
  expect_s3_class(gl, "tbl_df")
  expect_equal(nrow(gl), 1L)
  expect_true("sigma" %in% names(gl))
  expect_true("f_stat" %in% names(gl))
  expect_true("partial_r2" %in% names(gl))
})


# ============================================================================
# Tests: print and summary
# ============================================================================

test_that("summary() and print() work for first-stage objects", {
  data(card, package = "ivreg2r")
  fit <- ivreg2(lwage ~ exper + expersq + black + south + smsa |
                  educ | nearc4 + nearc2, data = card, first_stage = TRUE)
  fs <- first_stage(fit)$educ

  s <- summary(fs)
  expect_s3_class(s, "summary.ivreg2_first_stage")

  out <- capture.output(print(s))
  expect_true(any(grepl("First-stage regression", out)))
  expect_true(any(grepl("Root MSE", out)))

  out2 <- capture.output(print(fs))
  expect_true(any(grepl("First-stage regression", out2)))
})

test_that("confint() works for first-stage objects", {
  data(card, package = "ivreg2r")
  fit <- ivreg2(lwage ~ exper + expersq + black + south + smsa |
                  educ | nearc4 + nearc2, data = card, first_stage = TRUE)
  fs <- first_stage(fit)$educ

  ci <- confint(fs)
  expect_equal(nrow(ci), 8L)
  expect_equal(ncol(ci), 2L)

  ci2 <- confint(fs, parm = "nearc4")
  expect_equal(nrow(ci2), 1L)
})


# ============================================================================
# Tests: no regressions
# ============================================================================

test_that("first_stage = FALSE (default) doesn't change existing behavior", {
  data(card, package = "ivreg2r")
  fit1 <- ivreg2(lwage ~ exper + expersq + black + south + smsa |
                   educ | nearc4 + nearc2, data = card)
  fit2 <- ivreg2(lwage ~ exper + expersq + black + south + smsa |
                   educ | nearc4 + nearc2, data = card, first_stage = TRUE)

  expect_equal(coef(fit1), coef(fit2))
  expect_equal(vcov(fit1), vcov(fit2))
  expect_equal(fit1$sigma, fit2$sigma)
  expect_equal(fit1$first_stage, fit2$first_stage)
})
