# ============================================================================
# Tests: Orthogonality Test / Instrument-Subset C-Statistic (Ticket J1)
# ============================================================================
#
# Tests H0: specified instruments satisfy orthogonality conditions.
# Difference-of-Sargan (IID) or difference-of-J (robust/cluster) statistic.
# Verifies against Stata ivreg2 fixtures (e(cstat), e(cstatp), e(cstatdf)).
#
# M-22 fixture re-base (planning/22-spec-matrix.md): this family moved off the Card/sim ad hoc data onto the canonical help-file bases (griliches76, abdata, nlswork), generated by tests/stata-benchmarks/generate-orthog-fixtures.do. `small` is NOT varied in the fixtures themselves — Stata's e(cstat)/e(cstatp)/e(cstatdf) are invariant to `small` (see that .do file's header) — so every fixture-comparison cell below fits both small = FALSE and small = TRUE against the same fixture and additionally asserts the two fits agree to machine precision.

# --- Bundled datasets (lazy-loaded with the package) ---
data(griliches, package = "ivreg2r")
data(abdata, package = "ivreg2r")
data(nlswork, package = "ivreg2r")

# gril_formula (H06, help.txt:1154) is now provided by helper-fixtures.R.

abdata_formula <- n ~ 1 | w + k + ys |
  d(w, 1) + d(k, 1) + d(ys, 1) + d(w, 2) + d(k, 2) + d(ys, 2)

nls_formula <- ln_wage ~ grade + age + ttl_exp | tenure | south + c_city + not_smsa


# ============================================================================
# Structural tests (no fixtures) — griliches base model
# ============================================================================

test_that("orthog is NULL when not requested", {
  fit <- ivreg2(gril_formula, data = griliches)
  expect_null(fit$diagnostics$orthog)
})

test_that("orthog = character(0) is silently skipped", {
  fit <- ivreg2(gril_formula, data = griliches, orthog = character(0))
  expect_null(fit$diagnostics$orthog)
})

test_that("orthog is NULL for OLS models", {
  fit <- ivreg2(mpg ~ wt + hp, data = mtcars, orthog = "wt")
  expect_null(fit$diagnostics)
})

test_that("orthog has all expected fields", {
  fit <- ivreg2(gril_formula, data = griliches, orthog = c("age", "mrt"))
  orth <- fit$diagnostics$orthog
  expect_type(orth, "list")
  expect_named(orth, c("stat", "p", "df", "test_name", "tested_vars"),
               ignore.order = TRUE)
  expect_equal(orth$tested_vars, c("age", "mrt"))
  expect_identical(orth$df, 2L)
  expect_equal(orth$test_name, "C (orthog)")
})

test_that("invalid orthog variable name produces error", {
  expect_error(
    ivreg2(gril_formula, data = griliches, orthog = "not_a_var"),
    "not in the instrument list"
  )
})

test_that("orthog rejects endogenous variable", {
  expect_error(
    ivreg2(gril_formula, data = griliches, orthog = "iq"),
    "not in the instrument list"
  )
})

test_that("orthog must be character or NULL", {
  expect_error(
    ivreg2(gril_formula, data = griliches, orthog = 1),
    "character vector or NULL"
  )
})

test_that("duplicate orthog entries are deduplicated with warning", {
  fit_single <- ivreg2(gril_formula, data = griliches, orthog = "age")
  expect_warning(
    fit_dup <- ivreg2(gril_formula, data = griliches, orthog = c("age", "age")),
    "duplicate entries"
  )
  expect_equal(fit_dup$diagnostics$orthog$stat,
               fit_single$diagnostics$orthog$stat)
  expect_equal(fit_dup$diagnostics$orthog$df,
               fit_single$diagnostics$orthog$df)
})

test_that("testing all but one overid instrument gives C = J_full when restricted is exactly identified", {
  # Model: 4 excluded instruments (med, kww, age, mrt), 1 endogenous (iq)
  # -> overid_df = 3. Testing 3 of the 4 (med, kww, age) leaves only mrt as
  # the restricted model's excluded instrument, so the restricted model is
  # exactly identified (overid_df_r = 0), J_r = 0, and C = J_full - 0 = J_full.
  fit <- ivreg2(gril_formula, data = griliches, orthog = c("med", "kww", "age"))
  expect_equal(fit$diagnostics$orthog$stat, fit$diagnostics$overid$stat,
               tolerance = 1e-10)
  expect_identical(fit$diagnostics$orthog$df, 3L)
})

test_that("orthog appears in glance output", {
  fit <- ivreg2(gril_formula, data = griliches, orthog = c("age", "mrt"))
  g <- glance(fit)
  expect_true("orthog_stat" %in% names(g))
  expect_true("orthog_p" %in% names(g))
  expect_false(is.na(g$orthog_stat))
  expect_false(is.na(g$orthog_p))
})

test_that("orthog is NA in glance when not requested", {
  fit <- ivreg2(gril_formula, data = griliches)
  g <- glance(fit)
  expect_true(is.na(g$orthog_stat))
  expect_true(is.na(g$orthog_p))
})


# ============================================================================
# Fixture comparisons
# ============================================================================
#
# compare_orthog() makes plain assertions (no test_that) so each cell below is one test_that block that skips cleanly if its fixture is missing, reads the fixture once, and fits the model only when the fixture exists — matching the structure of the other re-based families (see test-stdp.R).

compare_orthog <- function(fit, fixture) {
  orth <- fit$diagnostics$orthog
  expect_false(is.null(orth))
  if (fixture$cstat == 0) {
    # Underidentified restricted model: Stata reports cstat=0 with missing
    # p/df; R returns stat=0 with df=0
    expect_equal(orth$stat, 0)
    expect_identical(orth$df, 0L)
  } else {
    expect_equal(orth$stat, fixture$cstat, tolerance = stata_tol$stat)
    expect_equal(orth$p, fixture$cstatp, tolerance = stata_tol$pval)
    expect_identical(orth$df, as.integer(fixture$cstatdf))
  }
}

orthog_cells <- list(
  list(name = "gril_orthog1 iid",
       fixture = "gril_orthog1_orthog_iid.csv",
       fit_args = list(gril_formula, data = griliches,
                       orthog = c("age", "mrt"))),
  list(name = "gril_orthog1 hc1",
       fixture = "gril_orthog1_orthog_hc1.csv",
       fit_args = list(gril_formula, data = griliches, vcov = "robust",
                       orthog = c("age", "mrt"))),
  list(name = "gril_orthogs iid (included regressor)",
       fixture = "gril_orthogs_orthog_iid.csv",
       fit_args = list(gril_formula, data = griliches, orthog = "s")),
  list(name = "gril_orthog1_dof iid",
       fixture = "gril_orthog1_dof_orthog_iid.csv",
       fit_args = list(gril_formula, data = griliches,
                       orthog = c("age", "mrt"), dofminus = 1L)),
  list(name = "gril_orthog1_dof hc1",
       fixture = "gril_orthog1_dof_orthog_hc1.csv",
       fit_args = list(gril_formula, data = griliches, vcov = "robust",
                       orthog = c("age", "mrt"), dofminus = 1L)),
  list(name = "gril_orthog2 iid (underidentified restricted)",
       fixture = "gril_orthog2_orthog_iid.csv",
       fit_args = list(gril_formula, data = griliches,
                       orthog = c("med", "kww", "age", "mrt"))),
  list(name = "ab_orthog1 cl",
       fixture = "ab_orthog1_orthog_cl.csv",
       fit_args = list(abdata_formula, data = abdata, tvar = "year",
                       ivar = "id", clusters = ~id, orthog = "d(w, 2)")),
  list(name = "nls_orthog1 cl2",
       fixture = "nls_orthog1_orthog_cl2.csv",
       fit_args = list(nls_formula, data = nlswork,
                       clusters = ~idcode + year, orthog = "south"))
)

test_stata_fixture_cells(orthog_cells, compare_orthog, slot = "orthog",
                         label_prefix = "orthog matches Stata")


# ============================================================================
# Factor variable support (term-label validation)
# ============================================================================

test_that("orthog accepts factor term labels and expands to columns", {
  set.seed(42)
  n <- 500
  region <- factor(sample(1:4, n, replace = TRUE))
  x1 <- rnorm(n)
  z1 <- rnorm(n)
  z2 <- rnorm(n)
  z3 <- rnorm(n)
  endo <- 0.5 * z1 + 0.3 * z2 + rnorm(n)
  y <- 1 + 0.5 * x1 + 0.8 * endo + rnorm(n)
  d <- data.frame(y, x1, endo, z1, z2, z3, region)

  # Factor as excluded instrument — orthog by term label
  fit <- ivreg2(y ~ x1 | endo | z1 + z2 + region,
                data = d, orthog = "region")
  expect_true(!is.null(fit$diagnostics$orthog))
  expect_true(is.finite(fit$diagnostics$orthog$stat))
  # df = number of columns tested (3 dummies for 4-level factor)
  expect_equal(fit$diagnostics$orthog$df, 3L)

  # Factor as exogenous instrument — orthog by term label
  # Need enough excluded instruments so restricted model is still identified
  z4 <- rnorm(n); z5 <- rnorm(n); z6 <- rnorm(n)
  d2 <- cbind(d, z4 = z4, z5 = z5, z6 = z6)
  fit2 <- ivreg2(y ~ x1 + region | endo | z1 + z2 + z3 + z4 + z5 + z6,
                 data = d2, orthog = "region")
  expect_true(!is.null(fit2$diagnostics$orthog))
  expect_true(is.finite(fit2$diagnostics$orthog$stat))
  expect_equal(fit2$diagnostics$orthog$df, 3L)

  # Column names (not term labels) are rejected — use term labels instead
  expect_error(
    ivreg2(y ~ x1 + region | endo | z1 + z2 + z3,
           data = d, orthog = c("region2", "region3")),
    "not in the instrument list"
  )
})

test_that("orthog + partial overlap produces an error, not silent degeneracy", {
  expect_error(
    ivreg2(gril_formula, data = griliches, partial = "expr", orthog = "expr"),
    "partialled out"
  )
})
