# ============================================================================
# Tests: stored moment-covariance S and weighting matrix W (fit$S / fit$W)
# Ticket F1 — Stata e(S)/e(W) parity (planning/24 §3; parity-deltas row 17)
#
# Part 1: R-only property tests + comparisons against e(S) fixtures that
#         already ship with the package (generated by
#         generate-wmatrix-fixtures.do — provenance verified per fixture).
# Part 2 (test blocks at the end): fixtures from
#         generate-stored-matrices-fixtures.do.
# ============================================================================

# --- Helpers (mirroring test-user-matrices.R conventions) -------------------

reorder_stata_to_r <- function(M, stata_order, r_order) {
  perm <- match(r_order, stata_order)
  M[perm, perm]
}

load_stata_matrix <- function(path, stata_order, r_order) {
  M <- as.matrix(read.csv(path))
  reorder_stata_to_r(M, stata_order, r_order)
}

# Stata e(S)/e(W) order: excluded instruments, included exogenous, _cons.
stata_z_order_overid <- c("nearc2", "nearc4", "exper", "expersq", "black",
                          "south", "(Intercept)")
r_z_order_overid <- c("(Intercept)", "exper", "expersq", "black", "south",
                      "nearc2", "nearc4")

card_path <- fixture_path("card_data.csv")
if (file.exists(card_path)) {
  card <- read.csv(card_path)
}

mroz_path <- fixture_path("mroz_data.csv")
have_mroz <- file.exists(mroz_path)
if (have_mroz) {
  mroz_fix <- read.csv(mroz_path)
}

# ============================================================================
# 1. Dimnames and presence across estimation paths
# ============================================================================

test_that("S and W carry instrument dimnames for IV fits", {
  skip_if(!file.exists(card_path), "Card dataset not found")
  fit <- ivreg2(lwage ~ exper + expersq + black + south | educ | nearc2 + nearc4,
                data = card)
  expect_identical(colnames(fit$S), colnames(fit$W))
  expect_identical(rownames(fit$S), colnames(fit$S))
  expect_setequal(colnames(fit$S),
                  c("(Intercept)", "exper", "expersq", "black", "south",
                    "nearc2", "nearc4"))
})

test_that("OLS fit stores S and W named by the X columns", {
  fit <- ivreg2(mpg ~ wt + hp, data = mtcars)
  expect_identical(colnames(fit$S), c("(Intercept)", "wt", "hp"))
  expect_identical(colnames(fit$W), c("(Intercept)", "wt", "hp"))
})

test_that("just-identified 2SLS stores S and W (no diagnostics omega path)", {
  skip_if(!file.exists(card_path), "Card dataset not found")
  fit <- ivreg2(lwage ~ exper + expersq + black + south | educ | nearc4,
                data = card)
  expect_true(is.matrix(fit$S))
  expect_true(is.matrix(fit$W))
  expect_identical(dim(fit$S), c(6L, 6L))
})

# ============================================================================
# 2. iid formulas (manual verification)
# ============================================================================

test_that("OLS iid S and W match the Stata m_omega formulas", {
  fit <- ivreg2(mpg ~ wt + hp, data = mtcars)
  X <- cbind(`(Intercept)` = 1, wt = mtcars$wt, hp = mtcars$hp)
  N <- nrow(mtcars)
  sigma2 <- fit$rss / N            # dofminus = 0
  S_manual <- sigma2 * crossprod(X) / N
  expect_equal(unname(fit$S), unname(S_manual), tolerance = 1e-12)
  # W = (1/sigma2) (X'X/N)^{-1}
  expect_equal(unname(fit$W %*% (crossprod(X) / N) * sigma2),
               diag(3), tolerance = 1e-10)
})

test_that("dofminus enters the iid S normalization (large-sample sigma)", {
  fit0 <- ivreg2(mpg ~ wt + hp, data = mtcars)
  fit5 <- ivreg2(mpg ~ wt + hp, data = mtcars, dofminus = 5L)
  N <- nrow(mtcars)
  # Same residuals, so S scales by (N - 0)/(N - 5)
  expect_equal(unname(fit5$S), unname(fit0$S) * N / (N - 5),
               tolerance = 1e-12)
})

test_that("small = TRUE does not change S or W", {
  fit  <- ivreg2(mpg ~ wt + hp, data = mtcars)
  fits <- ivreg2(mpg ~ wt + hp, data = mtcars, small = TRUE)
  expect_equal(fit$S, fits$S, tolerance = 1e-14)
  expect_equal(fit$W, fits$W, tolerance = 1e-14)
})

# ============================================================================
# 3. Weighted robust S (manual verification)
# ============================================================================

test_that("aweight robust S equals the weighted score crossproduct / (N - dofminus)", {
  skip_if(!file.exists(card_path), "Card dataset not found")
  fit <- ivreg2(lwage ~ exper + expersq + black + south | educ | nearc2 + nearc4,
                data = card, weights = weight, vcov = "robust")
  cc <- card[stats::complete.cases(
    card[c("lwage", "exper", "expersq", "black", "south", "educ",
           "nearc2", "nearc4", "weight")]), ]
  Z <- cbind(`(Intercept)` = 1, as.matrix(
    cc[c("exper", "expersq", "black", "south", "nearc2", "nearc4")]))
  N <- nrow(cc)
  w_raw <- as.numeric(cc$weight)        # integer NLS weights overflow in *
  w <- w_raw * N / sum(w_raw)           # normalized to sum to N
  e <- fit$residuals
  # Stata m_omega HC with aweights: wv = (w*wf)^2, i.e. scores = w*e*Z
  # (.hc_meat, vcov-robust.R — the w^2 e^2 convention, ticket E4)
  S_manual <- crossprod(Z * (w^2 * e^2), Z) / N   # dofminus = 0
  expect_equal(unname(fit$S[colnames(Z), colnames(Z)]), unname(S_manual),
               tolerance = 1e-10)
})

# ============================================================================
# 4. GMM paths: W is the inverse of the defining S
# ============================================================================

test_that("gmm2s: W %*% S = I and S is the step-1 omega", {
  skip_if(!file.exists(card_path), "Card dataset not found")
  fit <- ivreg2(lwage ~ exper + expersq + black + south | educ | nearc2 + nearc4,
                data = card, method = "gmm2s", vcov = "robust")
  L <- ncol(fit$S)
  expect_equal(unname(fit$W %*% fit$S), diag(L), tolerance = 1e-10)
  # step-1 omega = robust 2SLS S of the same spec
  fit_2sls <- ivreg2(lwage ~ exper + expersq + black + south | educ |
                       nearc2 + nearc4,
                     data = card, vcov = "robust")
  expect_equal(fit$S, fit_2sls$S, tolerance = 1e-12)
})

test_that("CUE and b0: W is the inverse of the converged/evaluated S", {
  skip_if(!file.exists(card_path), "Card dataset not found")
  fit_cue <- ivreg2(lwage ~ exper + expersq + black + south | educ |
                      nearc2 + nearc4,
                    data = card, method = "cue", vcov = "robust")
  L <- ncol(fit_cue$S)
  expect_equal(unname(fit_cue$W %*% fit_cue$S), diag(L), tolerance = 1e-10)

  fit_rob <- ivreg2(lwage ~ exper + expersq + black + south | educ |
                      nearc2 + nearc4,
                    data = card, vcov = "robust")
  fit_b0 <- ivreg2(lwage ~ exper + expersq + black + south | educ |
                     nearc2 + nearc4,
                   data = card, vcov = "robust", b0 = coef(fit_rob))
  expect_true(is.matrix(fit_b0$S))
  expect_equal(unname(fit_b0$W %*% fit_b0$S), diag(L), tolerance = 1e-10)
})

# ============================================================================
# 5. LIML / k-class: S stored, W NULL by design
# ============================================================================

test_that("LIML, Fuller, and kclass store S but no W", {
  skip_if(!file.exists(card_path), "Card dataset not found")
  f <- lwage ~ exper + expersq + black + south | educ | nearc2 + nearc4
  for (args in list(list(method = "liml"),
                    list(fuller = 1),
                    list(kclass = 1.05))) {
    fit <- do.call(ivreg2, c(list(formula = f, data = card), args))
    expect_true(is.matrix(fit$S))
    expect_null(fit$W)
  }
})

test_that("LIML iid S uses the k-class residuals (matches s_liml)", {
  skip_if(!file.exists(card_path), "Card dataset not found")
  fit <- ivreg2(lwage ~ exper + expersq + black + south | educ |
                  nearc2 + nearc4,
                data = card, method = "liml")
  cc <- card[stats::complete.cases(
    card[c("lwage", "exper", "expersq", "black", "south", "educ",
           "nearc2", "nearc4")]), ]
  Z <- cbind(`(Intercept)` = 1, as.matrix(
    cc[c("exper", "expersq", "black", "south", "nearc2", "nearc4")]))
  N <- nrow(cc)
  sigma2 <- sum(fit$residuals^2) / N
  S_manual <- sigma2 * crossprod(Z) / N
  expect_equal(unname(fit$S[colnames(Z), colnames(Z)]), unname(S_manual),
               tolerance = 1e-10)
})

# ============================================================================
# 6. Round-trip: the e(S) reuse workflow (help.txt:1156-1198)
# ============================================================================

test_that("refitting with smatrix = fit$S reproduces the gmm2s fit exactly", {
  skip_if(!file.exists(card_path), "Card dataset not found")
  f <- lwage ~ exper + expersq + black + south | educ | nearc2 + nearc4
  fit <- ivreg2(f, data = card, method = "gmm2s", vcov = "robust")
  refit <- ivreg2(f, data = card, method = "gmm2s", vcov = "robust",
                  smatrix = fit$S)
  expect_equal(coef(refit), coef(fit), tolerance = 1e-12)
  expect_equal(vcov(refit), vcov(fit), tolerance = 1e-12)
  expect_equal(refit$diagnostics$overid$stat, fit$diagnostics$overid$stat,
               tolerance = 1e-10)
})

# ============================================================================
# 7. Echo semantics for user matrices
# ============================================================================

test_that("user smatrix is echoed as fit$S with dimnames; smatrix field unchanged", {
  skip_if(!file.exists(card_path), "Card dataset not found")
  f <- lwage ~ exper + expersq + black + south | educ | nearc2 + nearc4
  base <- ivreg2(f, data = card, vcov = "robust")
  S_user <- unname(base$S)               # strip names: echo must restore them
  fit <- ivreg2(f, data = card, vcov = "robust", smatrix = S_user)
  expect_equal(unname(fit$S), S_user, tolerance = 1e-14)
  expect_identical(colnames(fit$S), colnames(base$S))
  # backward-compat raw echo field keeps the user's matrix as supplied
  expect_equal(fit$smatrix, S_user, tolerance = 1e-14)
  # smatrix-only implies gmm2s, so W = solve(S) (Stata s_gmm1s:5316-5326)
  expect_equal(unname(fit$W %*% fit$S), diag(ncol(fit$S)), tolerance = 1e-10)
})

test_that("user wmatrix is echoed as fit$W for gmmw and gmm2s+wmatrix", {
  skip_if(!file.exists(card_path), "Card dataset not found")
  f <- lwage ~ exper + expersq + black + south | educ | nearc2 + nearc4
  W_user <- diag(7)
  fit_w <- ivreg2(f, data = card, vcov = "robust", wmatrix = W_user)
  expect_identical(fit_w$method, "gmmw")
  expect_equal(unname(fit_w$W), W_user, tolerance = 1e-14)
  fit_w2 <- ivreg2(f, data = card, vcov = "robust", wmatrix = W_user,
                   method = "gmm2s")
  expect_equal(unname(fit_w2$W), W_user, tolerance = 1e-14)
  # but S differs between the two (W-step residuals vs final gmmw residuals
  # both feed omega; equality would be a coincidence, just check presence)
  expect_true(is.matrix(fit_w$S))
  expect_true(is.matrix(fit_w2$S))
})

test_that("ignored wmatrix (iid, no gmm2s) leaves W on the 1-step formula", {
  skip_if(!file.exists(card_path), "Card dataset not found")
  f <- lwage ~ exper + expersq + black + south | educ | nearc2 + nearc4
  expect_warning(
    fit <- ivreg2(f, data = card, wmatrix = diag(7)),
    "`wmatrix` is ignored"
  )
  plain <- ivreg2(f, data = card)
  expect_equal(fit$W, plain$W, tolerance = 1e-14)
  expect_equal(fit$S, plain$S, tolerance = 1e-14)
})

# ============================================================================
# 8. Invariances
# ============================================================================

test_that("noid does not change S or W", {
  skip_if(!file.exists(card_path), "Card dataset not found")
  f <- lwage ~ exper + expersq + black + south | educ | nearc2 + nearc4
  fit  <- ivreg2(f, data = card, vcov = "robust")
  fitn <- ivreg2(f, data = card, vcov = "robust", noid = TRUE)
  expect_equal(fit$S, fitn$S, tolerance = 1e-14)
  expect_equal(fit$W, fitn$W, tolerance = 1e-14)
})

# ============================================================================
# 9. Comparisons against e(S) fixtures already on disk
#    (generate-wmatrix-fixtures.do; provenance per fixture noted below.
#     gmm2s posts e(S) from step-1 2SLS residuals, so it equals the plain
#     2SLS e(S) for the same spec and VCE.)
# ============================================================================

test_that("robust 2SLS fit$S matches Stata e(S) [card_overid_smat_S_robust]", {
  fixture <- fixture_path("card_overid_smat_S_robust.csv")
  skip_if(!file.exists(fixture), "Fixture not found")
  skip_if(!file.exists(card_path), "Card dataset not found")
  # Generated by: ivreg2 lwage exper expersq black south (educ=nearc2 nearc4),
  #               robust gmm2s   (generate-wmatrix-fixtures.do:219-221)
  S_stata <- load_stata_matrix(fixture, stata_z_order_overid, r_z_order_overid)
  fit <- ivreg2(lwage ~ exper + expersq + black + south | educ | nearc2 + nearc4,
                data = card, vcov = "robust")
  expect_equal(unname(fit$S[r_z_order_overid, r_z_order_overid]),
               unname(S_stata), tolerance = stata_tol$vcov)
})

test_that("iid 2SLS fit$S matches Stata e(S) [card_overid_wmat_from_iid_W]", {
  fixture <- fixture_path("card_overid_wmat_from_iid_W.csv")
  skip_if(!file.exists(fixture), "Fixture not found")
  skip_if(!file.exists(card_path), "Card dataset not found")
  # Despite the file name, this IS e(S) from an iid run:
  # ivreg2 lwage exper expersq black south (educ=nearc2 nearc4)
  # (generate-wmatrix-fixtures.do:267-269)
  S_stata <- load_stata_matrix(fixture, stata_z_order_overid, r_z_order_overid)
  fit <- ivreg2(lwage ~ exper + expersq + black + south | educ | nearc2 + nearc4,
                data = card)
  expect_equal(unname(fit$S[r_z_order_overid, r_z_order_overid]),
               unname(S_stata), tolerance = stata_tol$vcov)
})

test_that("cluster fit$S matches Stata e(S) [card_overid_smat_S_cluster]", {
  fixture <- fixture_path("card_overid_smat_S_cluster.csv")
  skip_if(!file.exists(fixture), "Fixture not found")
  skip_if(!file.exists(card_path), "Card dataset not found")
  # Generated by: ivreg2 ..., cluster(age) gmm2s
  # (generate-wmatrix-fixtures.do:298-300)
  S_stata <- load_stata_matrix(fixture, stata_z_order_overid, r_z_order_overid)
  fit <- ivreg2(lwage ~ exper + expersq + black + south | educ | nearc2 + nearc4,
                data = card, clusters = ~ age)
  expect_equal(unname(fit$S[r_z_order_overid, r_z_order_overid]),
               unname(S_stata), tolerance = stata_tol$vcov)
})
