# ============================================================================
# Tests: ivreg2 help-file worked examples.
# Generated by generate-helpfile-fixtures.do.
#
# ----------------------------------------------------------------------------
# COVERAGE LEDGER — all 55 distinct `ivreg2` invocations in the help file's
# Examples section (H01-H105), by home:
# ----------------------------------------------------------------------------
#
# tested-here (griliches76, mroz, phillips, abdata, grunfeld, nlswork; 38
# commands, generate-helpfile-fixtures.do):
#   H03/H23, H04, H06, H07, H11, H13, H14, H16, H18, H20, H22, H25, H26, H27,
#   H28 (griliches, 15)
#   H31/H36, H33, H41/H46, H50, H54, H61, H66, H68 (mroz, 8)
#   H79, H80, H81 (phillips, 3)
#   H89, H90 (as bw=8), H91, H92 (as bw=8) (abdata, 4)
#   H95, H96, H97, H98, H99 (grunfeld, 5)
#   H103, H104, H105 (nlswork, 3)
#
# test-hols.R (empty-endogenous `(=z)` / HOLS syntax, ticket F3; 4 commands):
#   H34, H35, H48, H52 (mroz)
#
# test-ts-operators.R (formula-level `l()`/`d()` time-series operators,
# ticket F4; 9 commands):
#   H72, H73, H74, H75, H76 (klein)
#   H83, H84, H85 (phillips)
#   H88 (abdata)
#
# documented-error (help file itself is wrong; both Stata and R correctly
# reject the command; 3 commands, all fixtured as `capture` + `assert` in
# generate-helpfile-fixtures.do, no coef/vcov/diagnostics CSVs):
#   H29 (griliches: partial + gmm2s infeasible, 8 moments > 7 clusters)
#   H90, H92 (abdata: bw(9) exceeds the T=9 timespan; bw(8) is identical)
#
# external-package (5 commands, no ivreg2r equivalent):
#   H05 ivhettest, H24 overid, H32 ivendog, H82 newey, H100 xtscc
#
# Reconciliation with help-file-specs.md's 55 `ivreg2` command rows
# (42 "yes" + 4 "yes-F3" + 9 "yes-F4"): the 38 fixtures tested here cover
# 41 rows, because three fixtured commands are each shared by two H-rows
# (H03/H23; H31/H36 — savefirst is a Stata bookkeeping no-op; H41/H46).
# 41 + 4 (test-hols.R) + 9 (test-ts-operators.R) + 1 (H29, documented
# error, no fixture) = 55. H90/H92 are counted once, in the tested-here
# rows (fixtured at bw=8); their documented-error entries above record the
# rejection of the help file's literal bw(9), asserted in the .do file and
# in the expect_error tests below. The 5 external-package rows are not
# `ivreg2` commands and sit outside the 55.
# ============================================================================

data(griliches, package = "ivreg2r")
data(mroz, package = "ivreg2r")
data(phillips, package = "ivreg2r")
data(abdata, package = "ivreg2r")
data(grunfeld, package = "ivreg2r")
data(nlswork, package = "ivreg2r")

mroz_lw <- mroz[!is.na(mroz$lwage), ]
nls_cc <- nlswork[complete.cases(
  nlswork[, c("ln_wage", "grade", "age", "ttl_exp", "tenure")]
), ]

# --- Fixture path helper ---
hf_path <- function(ds, kind, hnn) {
  fixture_path(sprintf("hf_%s_%s_%s.csv", ds, kind, hnn))
}

# --- Sentinels: one per dataset block, keyed on the first fixture written ---
have_hf_gril <- file.exists(hf_path("gril", "coef", "H03"))
have_hf_mroz <- file.exists(hf_path("mroz", "coef", "H31"))
have_hf_phil <- file.exists(hf_path("phil", "coef", "H79"))
have_hf_ab <- file.exists(hf_path("ab", "coef", "H89"))
have_hf_grun <- file.exists(hf_path("grun", "coef", "H95"))
have_hf_nls <- file.exists(hf_path("nls", "coef", "H103"))

# Name translation (Stata term -> canonical R term label) uses the shared translate_stata_xi_names() helper (helper-fixtures.R); griliches uses `xi i.year`, generating `_Iyear_NN` dummies, and everything else maps 1:1 except the constant.

# ============================================================================
# Diagnostics field mapping: Stata e()-style column name -> R fit accessor
# ============================================================================

.hf_diag_value <- function(fit, col) {
  d <- fit$diagnostics
  switch(col,
    r2       = fit$r.squared,
    r2_a     = fit$adj.r.squared,
    r2u      = fit$r2u,
    r2c      = fit$r2c,
    rss      = fit$rss,
    rmse     = fit$sigma,
    F_stat   = fit$model_f,
    F_p      = fit$model_f_p,
    F_df1    = fit$model_f_df1,
    F_df2    = fit$model_f_df2,
    sargan   = if (!is.null(d$overid)) d$overid$stat else NA_real_,
    sarganp  = if (!is.null(d$overid)) d$overid$p else NA_real_,
    sargandf = if (!is.null(d$overid)) d$overid$df else NA_real_,
    j        = if (!is.null(d$overid)) d$overid$stat else NA_real_,
    jp       = if (!is.null(d$overid)) d$overid$p else NA_real_,
    jdf      = if (!is.null(d$overid)) d$overid$df else NA_real_,
    idstat   = if (!is.null(d$underid)) d$underid$stat else NA_real_,
    idp      = if (!is.null(d$underid)) d$underid$p else NA_real_,
    iddf     = if (!is.null(d$underid)) d$underid$df else NA_real_,
    cdf      = if (!is.null(d$weak_id)) d$weak_id$stat else NA_real_,
    widstat  = if (!is.null(d$weak_id_robust)) d$weak_id_robust$stat
               else if (!is.null(d$weak_id)) d$weak_id$stat else NA_real_,
    arf      = if (!is.null(d$anderson_rubin)) d$anderson_rubin$f_stat
               else NA_real_,
    arfp     = if (!is.null(d$anderson_rubin)) d$anderson_rubin$f_p
               else NA_real_,
    archi2   = if (!is.null(d$anderson_rubin)) d$anderson_rubin$chi2_stat
               else NA_real_,
    archi2p  = if (!is.null(d$anderson_rubin)) d$anderson_rubin$chi2_p
               else NA_real_,
    ardf     = if (!is.null(d$anderson_rubin)) d$anderson_rubin$f_df1
               else NA_real_,
    ardf_r   = if (!is.null(d$anderson_rubin)) d$anderson_rubin$f_df2
               else NA_real_,
    cstat    = if (!is.null(d$orthog)) d$orthog$stat else NA_real_,
    cstatp   = if (!is.null(d$orthog)) d$orthog$p else NA_real_,
    cstatdf  = if (!is.null(d$orthog)) d$orthog$df else NA_real_,
    sstat    = if (!is.null(d$stock_wright)) d$stock_wright$stat else NA_real_,
    sstatp   = if (!is.null(d$stock_wright)) d$stock_wright$p else NA_real_,
    sstatdf  = if (!is.null(d$stock_wright)) d$stock_wright$df else NA_real_,
    estat    = if (!is.null(d$endogeneity)) d$endogeneity$stat else NA_real_,
    estatp   = if (!is.null(d$endogeneity)) d$endogeneity$p else NA_real_,
    estatdf  = if (!is.null(d$endogeneity)) d$endogeneity$df else NA_real_,
    redstat  = if (!is.null(d$redundancy)) d$redundancy$stat else NA_real_,
    redp     = if (!is.null(d$redundancy)) d$redundancy$p else NA_real_,
    reddf    = if (!is.null(d$redundancy)) d$redundancy$df else NA_real_,
    N_clust  = fit$n_clusters %||% NA_real_,
    N_clust1 = fit$n_clusters1 %||% NA_real_,
    N_clust2 = fit$n_clusters2 %||% NA_real_,
    NA_real_
  )
}

# Columns with no direct R-side equivalent among the fitted models in this
# fixture set: K/L are the .do file's own rankxx/rankzz bookkeeping (not a
# fit quantity); kclass/lambda/fuller/arubin* apply only to LIML-family
# fits, none of which appear here (the help file's LIML examples are all on
# klein, covered by test-ts-operators.R) — confirmed always missing in every
# hf_*_diagnostics_*.csv fixture, so the comparison loop never reaches them.
.hf_diag_skip <- c("K", "L", "kclass", "lambda", "fuller",
                    "arubin", "arubinp", "arubin_lin", "arubin_linp",
                    "arubindf")
.hf_diag_exact <- c("F_df1", "F_df2", "jdf", "sargandf", "iddf", "ardf",
                     "ardf_r", "cstatdf", "sstatdf", "estatdf", "reddf",
                     "N_clust", "N_clust1", "N_clust2")
.hf_diag_pval <- c("F_p", "jp", "sarganp", "idp", "arfp", "archi2p",
                    "sstatp", "estatp", "cstatp", "redp")

# ============================================================================
# compare_hf(): coefficients + SEs, full VCV, and every non-missing
# diagnostics column against a Stata help-file fixture set.
# ============================================================================

compare_hf <- function(fit, ds, hnn, tol_coef = stata_tol$coef,
                       tol_se = stata_tol$se) {
  # --- Coefficients and SEs ---
  coef_fx <- read.csv(hf_path(ds, "coef", hnn), stringsAsFactors = FALSE)
  coef_fx$term_r <- translate_stata_xi_names(coef_fx$term)
  b <- coef(fit)
  se <- sqrt(diag(vcov(fit)))
  testthat::expect_setequal(coef_fx$term_r, names(b))
  for (i in seq_len(nrow(coef_fx))) {
    nm <- coef_fx$term_r[i]
    testthat::expect_equal(unname(b[nm]), coef_fx$estimate[i],
                           tolerance = tol_coef,
                           info = paste(ds, hnn, "coef", nm))
    testthat::expect_equal(unname(se[nm]), coef_fx$std_error[i],
                           tolerance = tol_se,
                           info = paste(ds, hnn, "se", nm))
  }

  # --- Full VCV ---
  vcov_fx <- read.csv(hf_path(ds, "vcov", hnn))
  vcov_cols <- grep("^vcov_", names(vcov_fx), value = TRUE)
  V_s <- as.matrix(vcov_fx[, vcov_cols, drop = FALSE])
  stata_terms <- translate_stata_xi_names(sub("^vcov_", "", vcov_cols))
  dimnames(V_s) <- list(stata_terms, stata_terms)
  V_r <- vcov(fit)
  testthat::expect_setequal(rownames(V_r), stata_terms)
  expect_vcov_equal(V_r, V_s)

  # --- Diagnostics: every non-missing column ---
  dx <- read_diagnostics(hf_path(ds, "diagnostics", hnn))
  testthat::expect_identical(fit$nobs, as.integer(dx$N))

  for (col in names(dx)) {
    if (col %in% .hf_diag_skip) next
    val <- dx[[col]]
    if (is.na(val)) next

    r_val <- .hf_diag_value(fit, col)
    if (is.na(r_val)) {
      # Two distinct reasons a Stata quantity has no R counterpart here:
      # (1) pure-OLS-via-ivreg2 models (no instrument structure at all,
      #     e.g. H90/H92) post no overid diagnostic (fit$diagnostics$overid
      #     is NULL) where Stata prints the exact-identification
      #     placeholder j=0/jdf=0 -- both mean "no overid test", agreement.
      # (2) genuinely not applicable to this fit; skip silently (mirrors
      #     validate-helpfile.qmd's compare_fixture() "skip" bucket).
      if (col %in% c("j", "jdf", "sargan", "sargandf") && val == 0) {
        testthat::expect_null(fit$diagnostics$overid,
                              info = paste(ds, hnn, col, "(exactly identified)"))
      }
      next
    }

    if (col %in% .hf_diag_exact) {
      testthat::expect_equal(round(r_val), round(val),
                             info = paste(ds, hnn, col))
    } else if (col %in% .hf_diag_pval) {
      testthat::expect_equal(r_val, val, tolerance = stata_tol$pval,
                             info = paste(ds, hnn, col))
    } else {
      testthat::expect_equal(r_val, val, tolerance = stata_tol$stat,
                             info = paste(ds, hnn, col))
    }
  }
}


# ============================================================================
# Griliches (1976): H03-H28 (help.txt:1128-1263)
# ============================================================================

test_that("H03/H23: Griliches 2SLS baseline (help.txt:1138)", {
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  fit <- ivreg2(
    lw ~ s + expr + tenure + rns + smsa + factor(year) | iq | med + kww + age + mrt,
    data = griliches
  )
  compare_hf(fit, "gril", "H03")
})

test_that("H04: Griliches 2SLS, small + ffirst (help.txt:1141)", {
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  fit <- ivreg2(
    lw ~ s + expr + tenure + rns + smsa + factor(year) | iq | med + kww + age + mrt,
    data = griliches, small = TRUE
  )
  compare_hf(fit, "gril", "H04")
})

test_that("H06: Griliches GMM2S + robust (help.txt:1154)", {
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  fit <- ivreg2(
    lw ~ s + expr + tenure + rns + smsa + factor(year) | iq | med + kww + age + mrt,
    data = griliches, method = "gmm2s", vcov = "robust"
  )
  compare_hf(fit, "gril", "H06")
})

gril_h07_fit <- NULL

test_that("H07: Griliches robust IV (help.txt:1162)", {
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  fit <- ivreg2(
    lw ~ s + expr + tenure + rns + smsa + factor(year) | iq | med + kww + age + mrt,
    data = griliches, vcov = "robust", x = TRUE
  )
  compare_hf(fit, "gril", "H07")
  gril_h07_fit <<- fit
})

test_that("H11: Griliches GMM2S + robust + user smatrix (help.txt:1162-1174)", {
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  skip_if(is.null(gril_h07_fit), "H07 fit unavailable")
  e <- residuals(gril_h07_fit)
  Z <- model.matrix(gril_h07_fit, component = "instruments")
  n <- nobs(gril_h07_fit)
  S <- crossprod(Z * as.numeric(e)) / n
  fit <- ivreg2(
    lw ~ s + expr + tenure + rns + smsa + factor(year) | iq | med + kww + age + mrt,
    data = griliches, method = "gmm2s", vcov = "robust", smatrix = S
  )
  compare_hf(fit, "gril", "H11")
})

test_that("H13: Griliches GMM2S + robust + user wmatrix (help.txt:1178-1182)", {
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  skip_if(is.null(gril_h07_fit), "H07 fit unavailable")
  e <- residuals(gril_h07_fit)
  Z <- model.matrix(gril_h07_fit, component = "instruments")
  n <- nobs(gril_h07_fit)
  S <- crossprod(Z * as.numeric(e)) / n
  W <- solve(S)
  fit <- ivreg2(
    lw ~ s + expr + tenure + rns + smsa + factor(year) | iq | med + kww + age + mrt,
    data = griliches, method = "gmm2s", vcov = "robust", wmatrix = W
  )
  compare_hf(fit, "gril", "H13")
})

gril_S0 <- NULL

test_that("H14: Griliches Ahn (1997) base GMM2S fit (help.txt:1189)", {
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  fit <- ivreg2(lw ~ 1 | iq | med + kww + age, data = griliches,
                method = "gmm2s")
  compare_hf(fit, "gril", "H14")
  gril_S0 <<- fit$S
})

test_that("H16: Ahn demo, kww excluded (smatrix reuse) (help.txt:1195)", {
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  skip_if(is.null(gril_S0), "H14 S0 unavailable")
  fit <- ivreg2(lw ~ med + age | iq | kww, data = griliches,
                method = "gmm2s", smatrix = gril_S0)
  compare_hf(fit, "gril", "H16")
})

test_that("H18: Ahn demo, med excluded (smatrix reuse) (help.txt:1201)", {
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  skip_if(is.null(gril_S0), "H14 S0 unavailable")
  fit <- ivreg2(lw ~ kww + age | iq | med, data = griliches,
                method = "gmm2s", smatrix = gril_S0)
  compare_hf(fit, "gril", "H18")
})

test_that("H20: Ahn demo, age excluded (smatrix reuse) (help.txt:1207)", {
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  skip_if(is.null(gril_S0), "H14 S0 unavailable")
  fit <- ivreg2(lw ~ med + kww | iq | age, data = griliches,
                method = "gmm2s", smatrix = gril_S0)
  compare_hf(fit, "gril", "H20")
})

test_that("H25: Griliches GMM2S, orthog(s) (help.txt:1235)", {
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  fit <- ivreg2(
    lw ~ s + expr + tenure + rns + smsa + factor(year) | iq | med + kww + age + mrt,
    data = griliches, method = "gmm2s", orthog = "s"
  )
  compare_hf(fit, "gril", "H25")
})

test_that("H26: Griliches GMM2S, orthog(age mrt) (help.txt:1242)", {
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  fit <- ivreg2(
    lw ~ s + expr + tenure + rns + smsa + factor(year) | iq | med + kww + age + mrt,
    data = griliches, method = "gmm2s", orthog = c("age", "mrt")
  )
  compare_hf(fit, "gril", "H26")
})

test_that("H27: Griliches cluster(year) (help.txt:1250)", {
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  # M = 7 year clusters vs L = 15 instruments: both Stata and R leave the
  # Hansen J and Stock-Wright statistics missing (singular cluster-robust
  # moment covariance), while still reporting the test's df -- confirmed by
  # the fixture (hf_gril_diagnostics_H27.csv: jdf populated, j blank). The
  # warnings are therefore expected, not a bug; this is the help file's own
  # example, verbatim.
  expect_warning(
    expect_warning(
      fit <- ivreg2(
        lw ~ s + expr + tenure + rns + smsa + factor(year) | iq | med + kww + age,
        data = griliches, clusters = ~year
      ),
      "Hansen J statistic not computed"
    ),
    "Stock-Wright.*rank-deficient"
  )
  compare_hf(fit, "gril", "H27")
})

test_that("H28: Griliches cluster(year) + partial(year dummies) (help.txt:1253)", {
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  # Same M = 7 vs L = 15 singularity as H27 (partialling out the year
  # dummies does not change the cluster/instrument count).
  expect_warning(
    expect_warning(
      fit <- ivreg2(
        lw ~ s + expr + tenure + rns + smsa + factor(year) | iq | med + kww + age,
        data = griliches, clusters = ~year, partial = "factor(year)"
      ),
      "Hansen J statistic not computed"
    ),
    "Stock-Wright.*rank-deficient"
  )
  compare_hf(fit, "gril", "H28")
})


# ============================================================================
# Mroz (1987): H31-H68 (help.txt:1268-1449)
# ============================================================================

test_that("H31/H36: Mroz 2SLS baseline (help.txt:1274; H36 at 1305 adds savefirst, a Stata bookkeeping no-op here)", {
  skip_if(!have_hf_mroz, "helpfile fixtures not found")
  fit <- ivreg2(lwage ~ exper + expersq | educ | age + kidslt6 + kidsge6,
                data = mroz_lw)
  compare_hf(fit, "mroz", "H31")
})

test_that("H33: Mroz endog(educ) (help.txt:1283)", {
  skip_if(!have_hf_mroz, "helpfile fixtures not found")
  fit <- ivreg2(lwage ~ exper + expersq | educ | age + kidslt6 + kidsge6,
                data = mroz_lw, endog = "educ")
  compare_hf(fit, "mroz", "H33")
})

test_that("H41/H46: Mroz robust IV (help.txt:1325/1350)", {
  skip_if(!have_hf_mroz, "helpfile fixtures not found")
  # savefirst (H41) is Stata bookkeeping only -- first stage is always
  # stored in ivreg2r, so the un-annotated H46 command fits identically.
  fit <- ivreg2(lwage ~ exper + expersq | educ | age + kidslt6 + kidsge6,
                data = mroz_lw, vcov = "robust")
  compare_hf(fit, "mroz", "H41")
})

test_that("H50: Mroz robust + redundant(age) (help.txt:1368)", {
  skip_if(!have_hf_mroz, "helpfile fixtures not found")
  fit <- ivreg2(lwage ~ exper + expersq | educ | age + kidslt6 + kidsge6,
                data = mroz_lw, vcov = "robust", redundant = "age")
  compare_hf(fit, "mroz", "H50")
})

test_that("H54: Mroz robust + AR/Stock-Wright (help.txt:1385)", {
  skip_if(!have_hf_mroz, "helpfile fixtures not found")
  fit <- ivreg2(lwage ~ exper + expersq | educ | age + kidslt6 + kidsge6,
                data = mroz_lw, vcov = "robust", reduced_form = "rf")
  compare_hf(fit, "mroz", "H54")
})

test_that("H61: Mroz reduced-form OLS, robust (help.txt:1416)", {
  skip_if(!have_hf_mroz, "helpfile fixtures not found")
  fit <- ivreg2(lwage ~ exper + expersq + age + kidslt6 + kidsge6,
                data = mroz_lw, vcov = "robust")
  compare_hf(fit, "mroz", "H61")
})

test_that("H66: Mroz bare OLS (b0 demo coefficient source) (help.txt:1440)", {
  skip_if(!have_hf_mroz, "helpfile fixtures not found")
  fit <- ivreg2(lwage ~ exper + expersq, data = mroz_lw)
  compare_hf(fit, "mroz", "H66")
})

test_that("H68: Mroz robust + b0 (help.txt:1446)", {
  skip_if(!have_hf_mroz, "helpfile fixtures not found")
  ols_fit <- lm(lwage ~ exper + expersq, data = mroz_lw)
  b0 <- c(educ = 0, coef(ols_fit))
  fit <- ivreg2(lwage ~ exper + expersq | educ | age + kidslt6 + kidsge6,
                data = mroz_lw, vcov = "robust", b0 = b0)
  compare_hf(fit, "mroz", "H68")
})


# ============================================================================
# Phillips: H79-H81 (help.txt:1494-1527)
# ============================================================================

test_that("H79: Phillips AC Bartlett bw(3) (help.txt:1501)", {
  skip_if(!have_hf_phil, "helpfile fixtures not found")
  fit <- ivreg2(cinf ~ unem, data = phillips, kernel = "bartlett", bw = 3,
                tvar = "year")
  compare_hf(fit, "phil", "H79")
})

test_that("H80: Phillips AC Quadratic Spectral, auto bandwidth (help.txt:1504)", {
  skip_if(!have_hf_phil, "helpfile fixtures not found")
  fit <- ivreg2(cinf ~ unem, data = phillips, kernel = "qs", bw = "auto",
                tvar = "year")
  compare_hf(fit, "phil", "H80")
})

test_that("H81: Phillips HAC Bartlett bw(3), robust, small (help.txt:1511)", {
  skip_if(!have_hf_phil, "helpfile fixtures not found")
  fit <- ivreg2(cinf ~ unem, data = phillips, kernel = "bartlett", bw = 3,
                vcov = "robust", small = TRUE, tvar = "year")
  compare_hf(fit, "phil", "H81")
})


# ============================================================================
# abdata: H89-H92 (help.txt:1533-1561)
# ============================================================================

test_that("H89: abdata Kiefer SEs (help.txt:1548)", {
  skip_if(!have_hf_ab, "helpfile fixtures not found")
  fit <- ivreg2(n ~ w + k, data = abdata, kiefer = TRUE, tvar = "year",
                ivar = "id")
  compare_hf(fit, "ab", "H89")
})

test_that("H90: abdata AC Truncated bw(8) [help file's bw(9) rejected] (help.txt:1551)", {
  skip_if(!have_hf_ab, "helpfile fixtures not found")
  fit <- ivreg2(n ~ w + k, data = abdata, kernel = "truncated", bw = 8,
                tvar = "year", ivar = "id")
  compare_hf(fit, "ab", "H90")
})

test_that("H91: abdata cluster(id) (help.txt:1558)", {
  skip_if(!have_hf_ab, "helpfile fixtures not found")
  fit <- ivreg2(n ~ w + k, data = abdata, clusters = ~id)
  compare_hf(fit, "ab", "H91")
})

test_that("H92: abdata HAC Truncated bw(8) + robust [help file's bw(9) rejected] (help.txt:1561)", {
  skip_if(!have_hf_ab, "helpfile fixtures not found")
  fit <- ivreg2(n ~ w + k, data = abdata, kernel = "truncated", bw = 8,
                vcov = "robust", tvar = "year", ivar = "id")
  compare_hf(fit, "ab", "H92")
})


# ============================================================================
# Grunfeld: H95-H99 (help.txt:1569-1601)
# ============================================================================

test_that("H95: Grunfeld AC Truncated bw(1) (help.txt:1576)", {
  skip_if(!have_hf_grun, "helpfile fixtures not found")
  fit <- ivreg2(invest ~ mvalue + kstock, data = grunfeld,
                kernel = "truncated", bw = 1, tvar = "year", ivar = "company")
  compare_hf(fit, "grun", "H95")
})

test_that("H96: Grunfeld HAC robust Truncated bw(1) (help.txt:1582)", {
  skip_if(!have_hf_grun, "helpfile fixtures not found")
  fit <- ivreg2(invest ~ mvalue + kstock, data = grunfeld, vcov = "robust",
                kernel = "truncated", bw = 1, tvar = "year", ivar = "company")
  compare_hf(fit, "grun", "H96")
})

test_that("H97: Grunfeld cluster(year) + robust + Truncated bw(1) (help.txt:1588)", {
  skip_if(!have_hf_grun, "helpfile fixtures not found")
  fit <- ivreg2(invest ~ mvalue + kstock, data = grunfeld, clusters = ~year,
                kernel = "truncated", bw = 1, tvar = "year", ivar = "company")
  compare_hf(fit, "grun", "H97")
})

grun_h98_fit <- NULL

test_that("H98: Grunfeld Driscoll-Kraay bw(2), small (help.txt:1595)", {
  skip_if(!have_hf_grun, "helpfile fixtures not found")
  fit <- ivreg2(invest ~ mvalue + kstock, data = grunfeld, dkraay = 2,
                small = TRUE, tvar = "year", ivar = "company")
  compare_hf(fit, "grun", "H98")
  grun_h98_fit <<- fit
})

grun_h99_fit <- NULL

test_that("H99: Grunfeld DK equivalence, cluster(year) + Bartlett bw(2), small (help.txt:1598)", {
  skip_if(!have_hf_grun, "helpfile fixtures not found")
  fit <- ivreg2(invest ~ mvalue + kstock, data = grunfeld, clusters = ~year,
                kernel = "bartlett", bw = 2, small = TRUE, tvar = "year",
                ivar = "company")
  compare_hf(fit, "grun", "H99")
  grun_h99_fit <<- fit
})


# ============================================================================
# nlswork: H103-H105 (help.txt:1604-1638)
# ============================================================================

test_that("H103: nlswork cluster(idcode) (help.txt:1618)", {
  skip_if(!have_hf_nls, "helpfile fixtures not found")
  fit <- ivreg2(ln_wage ~ grade + age + ttl_exp + tenure, data = nls_cc,
                clusters = ~idcode)
  compare_hf(fit, "nls", "H103")
})

test_that("H104: nlswork two-way cluster(idcode year) (help.txt:1628)", {
  skip_if(!have_hf_nls, "helpfile fixtures not found")
  fit <- ivreg2(ln_wage ~ grade + age + ttl_exp + tenure, data = nls_cc,
                clusters = ~idcode + year)
  compare_hf(fit, "nls", "H104")
})

test_that("H105: nlswork two-way cluster + Truncated bw(2) (help.txt:1637)", {
  skip_if(!have_hf_nls, "helpfile fixtures not found")
  # nlswork is an unbalanced panel (workers observed in non-consecutive
  # years); the kernel-weighted VCE's time index legitimately has gaps.
  # Stata's own log for this example prints the same warning ("time
  # variable year has ... gap(s) in relevant range").
  expect_warning(
    fit <- ivreg2(ln_wage ~ grade + age + ttl_exp + tenure, data = nls_cc,
                  clusters = ~idcode + year, kernel = "truncated", bw = 2,
                  tvar = "year", ivar = "idcode"),
    "gap"
  )
  compare_hf(fit, "nls", "H105")
})


# ============================================================================
# Equivalence property tests (no extra fixtures; help-file demo claims)
# ============================================================================

test_that("widstat equals the first-stage F (H36-H45 savefirst demo)", {
  skip_if(!have_hf_mroz, "helpfile fixtures not found")
  fit <- ivreg2(lwage ~ exper + expersq | educ | age + kidslt6 + kidsge6,
                data = mroz_lw, vcov = "robust", first_stage = TRUE)
  fs_f <- fit$first_stage$educ$f_stat
  expect_equal(fit$diagnostics$weak_id_robust$stat, fs_f,
               tolerance = stata_tol$stat)
})

test_that("Ahn (1997): H14 J equals the Wald test of included regressors in each smatrix refit (H14-H21, help.txt:1183-1210)", {
  # The help file's Ahn (1997) demo: the Hansen J of the overidentified
  # H14 fit equals the Wald test that the "extra" instruments have zero
  # coefficients when they are moved into the regression as included
  # regressors, PROVIDED the refit reuses the H14 fit's moment covariance
  # (smatrix = fit14$S) -- irrespective of which instrument stays excluded.
  # Stata runs `test med age` / `test kww age` / `test med kww` after the
  # three refits; here the same quadratic form b' V^-1 b is built from
  # each refit's coef/vcov. This exercises the fit$S export end-to-end.
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  fit14 <- ivreg2(lw ~ 1 | iq | med + kww + age, data = griliches,
                  method = "gmm2s")
  J14 <- fit14$diagnostics$overid$stat
  S0 <- fit14$S
  expect_equal(dim(S0), c(4L, 4L))
  expect_true(all(c("(Intercept)", "med", "kww", "age") %in% colnames(S0)))

  wald_included <- function(fit, vars) {
    b <- coef(fit)[vars]
    V <- vcov(fit)[vars, vars]
    drop(t(b) %*% solve(V) %*% b)
  }
  fit16 <- ivreg2(lw ~ med + age | iq | kww, data = griliches,
                  method = "gmm2s", smatrix = S0)
  fit18 <- ivreg2(lw ~ kww + age | iq | med, data = griliches,
                  method = "gmm2s", smatrix = S0)
  fit20 <- ivreg2(lw ~ med + kww | iq | age, data = griliches,
                  method = "gmm2s", smatrix = S0)
  expect_equal(wald_included(fit16, c("med", "age")), J14,
               tolerance = 1e-8)
  expect_equal(wald_included(fit18, c("kww", "age")), J14,
               tolerance = 1e-8)
  expect_equal(wald_included(fit20, c("med", "kww")), J14,
               tolerance = 1e-8)
})

test_that("AR stat equals the reduced-form Wald (H58-H63 demo)", {
  skip_if(!have_hf_mroz, "helpfile fixtures not found")
  fit_ar <- ivreg2(lwage ~ exper + expersq | educ | age + kidslt6 + kidsge6,
                   data = mroz_lw, vcov = "robust", reduced_form = "rf")
  fit_rf <- ivreg2(lwage ~ exper + expersq + age + kidslt6 + kidsge6,
                   data = mroz_lw, vcov = "robust")
  # Manual Wald chi-sq for H0: coefs on (age, kidslt6, kidsge6) = 0, using
  # fit_rf's own coef/vcov subset (the H58-H63 demo's "test ... ; di
  # r(chi2)" step, help.txt:1416-1422).
  wald_terms <- c("age", "kidslt6", "kidsge6")
  b_sub <- coef(fit_rf)[wald_terms]
  V_sub <- vcov(fit_rf)[wald_terms, wald_terms]
  w <- as.numeric(t(b_sub) %*% solve(V_sub) %*% b_sub)
  expect_equal(fit_ar$diagnostics$anderson_rubin$chi2_stat, w,
               tolerance = stata_tol$stat)
})

test_that("vcov(H89 kiefer) equals vcov(H90 truncated bw=8)", {
  skip_if(!have_hf_ab, "helpfile fixtures not found")
  fit_kiefer <- ivreg2(n ~ w + k, data = abdata, kiefer = TRUE,
                       tvar = "year", ivar = "id")
  fit_bw8 <- ivreg2(n ~ w + k, data = abdata, kernel = "truncated", bw = 8,
                    tvar = "year", ivar = "id")
  expect_equal(unname(vcov(fit_kiefer)), unname(vcov(fit_bw8)),
               tolerance = 1e-10)
})

test_that("vcov(H98 Driscoll-Kraay) equals vcov(H99 cluster+bartlett bw=2)", {
  skip_if(!have_hf_grun, "helpfile fixtures not found")
  skip_if(is.null(grun_h98_fit) || is.null(grun_h99_fit), "fits unavailable")
  expect_equal(unname(vcov(grun_h98_fit)), unname(vcov(grun_h99_fit)),
               tolerance = 1e-10)
})

# H91 (cluster(id)) and H92 (bw(8) + truncated + robust) are NOT asserted
# equal here: help-file-specs.md and validate-helpfile.qmd document them as
# two separate salvaged examples of the SAME bw(9) help-file bug, and
# neither source claims H91 == H92. They are different estimators in
# general, coinciding only when the kernel-implied bandwidth spans the full
# within-panel timespan. bw(8) IS that full-span case for abdata (T = 9),
# and the coincidence is asserted on provable grounds in
# test-vcov-cluster-kernel.R ("cluster-robust equals robust truncated
# kernel at maximum bandwidth"); it stays unasserted here because no
# help-file source states it.


# ============================================================================
# Documented divergences
# ============================================================================

test_that("H22: Griliches CUE robust converges to Stata's basin (flat-objective cell)", {
  # The CUE ratio objective on this 13-regressor model has its minimum in a
  # degenerate basin (R^2 = -54, J = 40.1) -- the documented ratio-objective
  # pathology of the CUE ESTIMATOR (Hausman et al. 2011), not an optimizer
  # bug. Stata's Newton-Raphson has always found it. Before the parscale fix,
  # R's unscaled BFGS stalled at its iteration cap at J = 67.5, and that stall
  # was recorded as an "intentional divergence". With
  # per-coordinate scaling, BFGS genuinely converges (code 0) into the same
  # basin as Stata (a 600-random-direction probe at relative radii 1e-3 to
  # 1e-1 found zero descent directions at the optimum; the old point had 55
  # of 200 -- it was not a critical point at all). The basin is extremely
  # flat, so coefficient agreement with the fixture is limited to flat-basin
  # resolution (observed max 0.74% relative; a ~9e-8 relative change in J
  # moves coefficients by ~0.3%) -- but J itself varies across the basin at
  # only that ~1e-7 relative scale, so J IS a full parity quantity here
  # even though the coefficients are not. The bands below assert BASIN
  # MEMBERSHIP for the coordinates: the old stall point and the
  # economically sensible GMM2S-like basin (iq about -0.0014, R^2 = 0.37)
  # sit far outside them.
  skip_if(!have_hf_gril, "helpfile fixtures not found")
  fx <- read.csv(hf_path("gril", "coef", "H22"), stringsAsFactors = FALSE)
  fx$term_r <- translate_stata_xi_names(fx$term)
  h22_formula <-
    lw ~ s + expr + tenure + rns + smsa + factor(year) | iq | med + kww + age + mrt

  expect_no_warning(
    fit <- ivreg2(h22_formula, data = griliches, method = "cue", vcov = "robust")
  )
  # (a) Hansen J parity against Stata's own e(j) at standard tolerance --
  # the exact basin identifier (observed gap 8.7e-8 relative, ~1000x margin;
  # the pre-parscale stall point sits 27 J-units = 68% away). R's b0
  # evaluation of the CUE objective at Stata's fixture coefficients
  # reproduces this e(j) to ~1e-11, so the two implementations' J
  # computations agree at the same beta (2026-07-06 second-opinion check).
  dx <- read_diagnostics(hf_path("gril", "diagnostics", "H22"))
  expect_equal(fit$diagnostics$overid$stat, dx$j, tolerance = stata_tol$stat)
  expect_equal(fit$diagnostics$overid$p, dx$jp, tolerance = stata_tol$pval)
  # (b) coefficients and SEs agree with Stata at flat-basin resolution.
  # Band derivation: coordinate displacement near a quadratic minimum scales
  # as sqrt of the objective gap, so a cross-platform J agreement of ~1e-6
  # relative (vs the 9e-8 observed here) predicts ~sqrt(1e-6/9e-8) * 0.74%
  # ~ 2.5% spread; 5% covers that while staying ~20x inside the iq
  # separation from the other basin (|iq_other - iq_fx|/|iq_fx| ~ 99.5%).
  b_r <- coef(fit)[fx$term_r]
  se_r <- sqrt(diag(vcov(fit)))[fx$term_r]
  expect_lt(max(abs(unname(b_r) - fx$estimate) / abs(fx$estimate)), 0.05)
  expect_lt(max(abs(unname(se_r) - fx$std_error) / abs(fx$std_error)), 0.05)
  # (c) the degenerate-basin signature: negative R^2 (the sensible basin has
  # R^2 = 0.37). For the two known basins this is implied by (a) -- R^2 is a
  # function of beta -- and is kept as self-documenting belt-and-suspenders
  # that survives any future loosening of the J band.
  expect_lt(fit$r.squared, 0)
})

test_that("H90/H92: bw(9) is rejected by both Stata and R (help.txt:1551/1561)", {
  # T = 9 (abdata timespan); bw() must be strictly less than the panel's
  # timespan, so bw(9) leaves no valid lag structure for the truncated
  # kernel. bw(8) (max lag = T - 1 = 8) is numerically identical because
  # the truncated kernel assigns weight 1 to every available lag -- see the
  # H90/H92 tests above for the salvaged bw(8) fixture comparisons. Both
  # Stata (r(198): "bandwidth cannot exceed timespan of data") and R reject
  # the help file's own command.
  expect_error(
    ivreg2(n ~ w + k, data = abdata, kernel = "truncated", bw = 9,
           tvar = "year", ivar = "id"),
    "time span"
  )
  expect_error(
    ivreg2(n ~ w + k, data = abdata, kernel = "truncated", bw = 9,
           vcov = "robust", tvar = "year", ivar = "id"),
    "time span"
  )
})

test_that("H29: partial + gmm2s is infeasible (help.txt:1261)", {
  # After partialling out the year dummies, 5 included + 3 excluded = 8
  # moment conditions remain against M = 7 year clusters, so the
  # cluster-robust S matrix has rank <= 7 < 8 and cannot be inverted. Stata
  # itself rejects this command (r(506): "optimal GMM weighting matrix not
  # unique"; see generate-helpfile-fixtures.do's `assert _rc != 0` for H29).
  expect_error(
    ivreg2(
      lw ~ s + expr + tenure + rns + smsa + factor(year) | iq | med + kww + age,
      data = griliches, clusters = ~year, partial = "factor(year)",
      method = "gmm2s"
    ),
    "not of full rank"
  )
})
