# ============================================================================
# Tests: First-Stage Diagnostics (Ticket E1)
# ============================================================================
#
# First-stage F-test, partial R², Shea partial R², and RMSE. Verifies against Stata ivreg2 fixtures.
#
# This family uses the canonical help-file bases (mroz, griliches76, abdata), generated by tests/stata-benchmarks/generate-firststage-fixtures.do. Stata's e(first) is verified byte-identical under `small` across iid/hc1/cluster variants in the retired card/sim fixtures, so this family's fixtures do NOT vary `small` -- every fixture-comparison cell below fits both small = FALSE and small = TRUE against the same fixture and additionally asserts the whole fit$first_stage object is equal either way.

# --- Bundled datasets (lazy-loaded with the package) ---
data(mroz, package = "ivreg2r")
data(griliches, package = "ivreg2r")
data(abdata, package = "ivreg2r")

mroz_formula <- lwage ~ exper + expersq | educ | age + kidslt6 + kidsge6
# mroz_justid_formula comes from helper-fixtures.R.
mroz_nocons_formula <- lwage ~ 0 | educ | age + kidslt6 + kidsge6

# gril_formula (H06, help.txt:1154) is now provided by helper-fixtures.R.

# ============================================================================
# Structural tests (no fixtures)
# ============================================================================

test_that("first_stage is NULL for OLS models", {
  fit <- ivreg2(mpg ~ wt + hp, data = mtcars)
  expect_null(fit$first_stage)
})

test_that("first_stage is named list with names == endogenous", {
  fit <- ivreg2(mroz_formula, data = mroz)
  expect_type(fit$first_stage, "list")
  expect_named(fit$first_stage, "educ")
})

test_that("first_stage has all expected fields", {
  fit <- ivreg2(mroz_formula, data = mroz)
  expected_fields <- c("f_stat", "f_p", "f_df1", "f_df2",
                       "partial_r2", "shea_partial_r2", "rmse",
                       "coefficients", "residuals", "fitted.values",
                       "sw_f", "sw_f_p", "sw_f_df1", "sw_f_df2",
                       "sw_chi2", "sw_chi2_p", "sw_partial_r2",
                       "ap_f", "ap_f_p", "ap_f_df1", "ap_f_df2",
                       "ap_chi2", "ap_chi2_p", "ap_partial_r2")
  expect_named(fit$first_stage$educ, expected_fields, ignore.order = TRUE)
})

test_that("first_stage coefficients/residuals/fitted have correct lengths", {
  fit <- ivreg2(mroz_formula, data = mroz)
  fs <- fit$first_stage$educ
  # Intercept + 2 exogenous (exper, expersq) + 3 excluded instruments (age, kidslt6, kidsge6)
  expect_length(fs$coefficients, 6L)
  expect_length(fs$residuals, fit$nobs)
  expect_length(fs$fitted.values, fit$nobs)
})

test_that("multi-endo first_stage has correct names", {
  fit <- ivreg2(ab_formula, data = abdata, tvar = "year", ivar = "id")
  expect_named(fit$first_stage, c("w", "k", "ys"))
})

test_that("K1=1: shea_partial_r2 equals partial_r2", {
  # With one endogenous regressor Shea's partial R2 reduces algebraically to
  # the ordinary partial R2; the two code paths agree to ~1e-14 (measured),
  # so 1e-11 leaves two decades of headroom.
  fit <- ivreg2(mroz_formula, data = mroz)
  fs <- fit$first_stage$educ
  expect_equal(fs$shea_partial_r2, fs$partial_r2, tolerance = 1e-11)
})

test_that("small does not change first-stage F-stat (IID)", {
  fit1 <- ivreg2(mroz_formula, data = mroz, small = FALSE)
  fit2 <- ivreg2(mroz_formula, data = mroz, small = TRUE)
  expect_equal(fit1$first_stage$educ$f_stat,
               fit2$first_stage$educ$f_stat)
})

test_that("small does not change first-stage F-stat (HC1)", {
  fit1 <- ivreg2(mroz_formula, data = mroz, vcov = "robust", small = FALSE)
  fit2 <- ivreg2(mroz_formula, data = mroz, vcov = "robust", small = TRUE)
  expect_equal(fit1$first_stage$educ$f_stat,
               fit2$first_stage$educ$f_stat)
})

test_that("K1=1: SW/AP F equals standard F", {
  fit <- ivreg2(mroz_formula, data = mroz)
  fs <- fit$first_stage$educ
  expect_equal(fs$sw_f, fs$f_stat)
  expect_equal(fs$ap_f, fs$f_stat)
  expect_equal(fs$sw_f_p, fs$f_p)
  expect_equal(fs$ap_f_p, fs$f_p)
})

test_that("K1=1: SW/AP partial R2 equals partial R2", {
  fit <- ivreg2(mroz_formula, data = mroz)
  fs <- fit$first_stage$educ
  expect_equal(fs$sw_partial_r2, fs$partial_r2)
  expect_equal(fs$ap_partial_r2, fs$partial_r2)
})

test_that("K1=1: SW/AP df1 equals L1", {
  # L1=1 (just identified)
  fit1 <- ivreg2(mroz_justid_formula, data = mroz)
  expect_identical(fit1$first_stage$educ$sw_f_df1, 1L)
  expect_identical(fit1$first_stage$educ$ap_f_df1, 1L)
  # L1=3 (overidentified)
  fit2 <- ivreg2(mroz_formula, data = mroz)
  expect_identical(fit2$first_stage$educ$sw_f_df1, 3L)
  expect_identical(fit2$first_stage$educ$ap_f_df1, 3L)
})

test_that("K1>1: SW/AP df1 equals L1 - K1 + 1", {
  fit <- ivreg2(ab_formula, data = abdata, tvar = "year", ivar = "id")
  # L1=6, K1=3 => Fdf1 = 4
  expect_identical(fit$first_stage$w$sw_f_df1, 4L)
  expect_identical(fit$first_stage$w$ap_f_df1, 4L)
  expect_identical(fit$first_stage$k$sw_f_df1, 4L)
  expect_identical(fit$first_stage$k$ap_f_df1, 4L)
  expect_identical(fit$first_stage$ys$sw_f_df1, 4L)
  expect_identical(fit$first_stage$ys$ap_f_df1, 4L)
})

test_that("K1=1: SW/AP identity holds with cluster VCE", {
  # griliches76 has no natural panel id, so this clusters on `tenure80` (23 groups, a variable from the 1980 follow-up survey that does not appear anywhere in gril_formula) rather than the retired synthetic sim_cluster data; the identity being tested (SW/AP collapse to plain F when K1=1) doesn't depend on what the cluster variable represents economically.
  # (Clustering on `year` or on `age` was tried first but both are degenerate here: `year` is already a regressor via factor(year), and `age` is already an excluded instrument, so clustering on either makes the within-cluster score for that column exactly zero and the cluster-robust Omega exactly singular.)
  fit <- ivreg2(gril_formula, data = griliches, clusters = ~tenure80)
  fs <- fit$first_stage$iq
  expect_equal(fs$sw_f, fs$f_stat)
  expect_equal(fs$ap_f, fs$f_stat)
  expect_equal(fs$sw_partial_r2, fs$partial_r2)
  expect_equal(fs$ap_partial_r2, fs$partial_r2)
})

test_that("K1=1: SW/AP identity holds with weights", {
  fit <- ivreg2(gril_formula, data = griliches_awt, weights = awt)
  fs <- fit$first_stage$iq
  expect_equal(fs$sw_f, fs$f_stat)
  expect_equal(fs$ap_f, fs$f_stat)
  expect_equal(fs$sw_partial_r2, fs$partial_r2)
  expect_equal(fs$ap_partial_r2, fs$partial_r2)
})

test_that("SW/AP partial R2 invariant to VCE type (multi-endo)", {
  fit_iid <- ivreg2(ab_formula, data = abdata, tvar = "year", ivar = "id",
                    vcov = "iid")
  fit_hc1 <- ivreg2(ab_formula, data = abdata, tvar = "year", ivar = "id",
                    vcov = "robust")
  for (endo in c("w", "k", "ys")) {
    expect_equal(fit_iid$first_stage[[endo]]$sw_partial_r2,
                 fit_hc1$first_stage[[endo]]$sw_partial_r2)
    expect_equal(fit_iid$first_stage[[endo]]$ap_partial_r2,
                 fit_hc1$first_stage[[endo]]$ap_partial_r2)
  }
})

# Multi-endo: Shea != partial R² (structural)
test_that("multi-endo: Shea partial R2 differs from partial R2", {
  fit <- ivreg2(ab_formula, data = abdata, tvar = "year", ivar = "id")
  # Shea should be strictly less than partial R² for multi-endo
  for (endo in c("w", "k", "ys")) {
    expect_true(fit$first_stage[[endo]]$shea_partial_r2 <
                fit$first_stage[[endo]]$partial_r2)
  }
})


# ============================================================================
# Helper: plain assertions for one fixture/endo combination (no test_that inside -- callers wrap one test_that per fixture cell, matching the structure of the other re-based families, e.g. test-diagnostics-redundancy.R)
# ============================================================================

check_firststage <- function(fit, fixture, endo_name) {
  fs <- fit$first_stage[[endo_name]]

  expect_equal(fs$rmse,
               get_fs_value(fixture, "rmse", endo_name),
               tolerance = stata_tol$coef)

  expect_equal(fs$partial_r2,
               get_fs_value(fixture, "pr2", endo_name),
               tolerance = stata_tol$stat)

  expect_equal(fs$shea_partial_r2,
               get_fs_value(fixture, "sheapr2", endo_name),
               tolerance = stata_tol$stat)

  expect_equal(fs$f_stat,
               get_fs_value(fixture, "F", endo_name),
               tolerance = stata_tol$stat)

  expect_identical(fs$f_df1,
                   as.integer(get_fs_value(fixture, "df", endo_name)))
  expect_identical(fs$f_df2,
                   as.integer(get_fs_value(fixture, "df_r", endo_name)))

  expect_equal(fs$f_p,
               get_fs_value(fixture, "pvalue", endo_name),
               tolerance = stata_tol$pval)

  # --- SW diagnostics ---
  expect_equal(fs$sw_f,
               get_fs_value(fixture, "SWF", endo_name),
               tolerance = stata_tol$stat)

  expect_identical(fs$sw_f_df1,
                   as.integer(get_fs_value(fixture, "SWFdf1", endo_name)))
  expect_identical(fs$sw_f_df2,
                   as.integer(get_fs_value(fixture, "SWFdf2", endo_name)))

  expect_equal(fs$sw_f_p,
               get_fs_value(fixture, "SWFp", endo_name),
               tolerance = stata_tol$pval)

  expect_equal(fs$sw_chi2,
               get_fs_value(fixture, "SWchi2", endo_name),
               tolerance = stata_tol$stat)

  expect_equal(fs$sw_chi2_p,
               get_fs_value(fixture, "SWchi2p", endo_name),
               tolerance = stata_tol$pval)

  expect_equal(fs$sw_partial_r2,
               get_fs_value(fixture, "SWr2", endo_name),
               tolerance = stata_tol$stat)

  # --- AP diagnostics ---
  expect_equal(fs$ap_f,
               get_fs_value(fixture, "APF", endo_name),
               tolerance = stata_tol$stat)

  expect_identical(fs$ap_f_df1,
                   as.integer(get_fs_value(fixture, "APFdf1", endo_name)))
  expect_identical(fs$ap_f_df2,
                   as.integer(get_fs_value(fixture, "APFdf2", endo_name)))

  expect_equal(fs$ap_f_p,
               get_fs_value(fixture, "APFp", endo_name),
               tolerance = stata_tol$pval)

  expect_equal(fs$ap_chi2,
               get_fs_value(fixture, "APchi2", endo_name),
               tolerance = stata_tol$stat)

  expect_equal(fs$ap_chi2_p,
               get_fs_value(fixture, "APchi2p", endo_name),
               tolerance = stata_tol$pval)

  expect_equal(fs$ap_partial_r2,
               get_fs_value(fixture, "APr2", endo_name),
               tolerance = stata_tol$stat)
}


# ============================================================================
# Fixture comparisons: 13 cells across mroz / griliches76 / abdata
# ============================================================================

firststage_cells <- list(
  list(name = "mroz iid",
       fixture = "mroz_fs_firststage_iid.csv",
       fit_args = list(mroz_formula, data = mroz),
       endos = "educ"),
  list(name = "mroz hc1",
       fixture = "mroz_fs_firststage_hc1.csv",
       fit_args = list(mroz_formula, data = mroz, vcov = "robust"),
       endos = "educ"),
  list(name = "mroz justid iid",
       fixture = "mroz_fs_justid_firststage_iid.csv",
       fit_args = list(mroz_justid_formula, data = mroz),
       endos = "educ"),
  list(name = "mroz justid hc1",
       fixture = "mroz_fs_justid_firststage_hc1.csv",
       fit_args = list(mroz_justid_formula, data = mroz, vcov = "robust"),
       endos = "educ"),
  list(name = "mroz nocons iid",
       fixture = "mroz_fs_nocons_firststage_iid.csv",
       fit_args = list(mroz_nocons_formula, data = mroz),
       endos = "educ"),
  list(name = "mroz nocons hc1",
       fixture = "mroz_fs_nocons_firststage_hc1.csv",
       fit_args = list(mroz_nocons_formula, data = mroz, vcov = "robust"),
       endos = "educ"),
  list(name = "griliches iid",
       fixture = "gril_fs_firststage_iid.csv",
       fit_args = list(gril_formula, data = griliches),
       endos = "iq"),
  list(name = "griliches aweight iid",
       fixture = "gril_fs_aw_firststage_iid.csv",
       fit_args = list(gril_formula, data = griliches_awt,
                       weights = quote(awt)),
       endos = "iq"),
  list(name = "griliches aweight hc1",
       fixture = "gril_fs_aw_firststage_hc1.csv",
       fit_args = list(gril_formula, data = griliches_awt,
                       weights = quote(awt), vcov = "robust"),
       endos = "iq"),
  # Restores the K1=1 x cluster intersection lost with the retired sim_cluster cells (tenure80 = arbitrary-but-real 23-group clustering, disclosed in the .do).
  list(name = "gril_fs cl (K1=1 x cluster, tenure80)",
       fixture = "gril_fs_firststage_cl.csv",
       fit_args = list(gril_formula, data = griliches, clusters = ~tenure80),
       endos = "iq"),
  list(name = "abdata iid",
       fixture = "ab_fs_firststage_iid.csv",
       fit_args = list(ab_formula, data = abdata, tvar = "year", ivar = "id"),
       endos = c("w", "k", "ys")),
  list(name = "abdata hc1",
       fixture = "ab_fs_firststage_hc1.csv",
       fit_args = list(ab_formula, data = abdata, tvar = "year", ivar = "id",
                       vcov = "robust"),
       endos = c("w", "k", "ys")),
  list(name = "abdata cluster(id)",
       fixture = "ab_fs_firststage_cl.csv",
       fit_args = list(ab_formula, data = abdata, tvar = "year", ivar = "id",
                       clusters = ~id),
       endos = c("w", "k", "ys")),
  list(name = "abdata aweight + cluster(id)",
       fixture = "ab_fs_aw_firststage_cl.csv",
       fit_args = list(ab_formula, data = abdata_awt, tvar = "year",
                       ivar = "id", weights = quote(abwt), clusters = ~id),
       endos = c("w", "k", "ys"))
)

for (cell in firststage_cells) {
  test_that(paste("first-stage matches Stata:", cell$name), {
    fixture_file <- fixture_path(cell$fixture)
    skip_if(!file.exists(fixture_file), "fixture not found")
    fixture <- read_firststage(fixture_file)

    fit <- do.call(ivreg2, c(cell$fit_args, list(small = FALSE)))
    fit_small <- do.call(ivreg2, c(cell$fit_args, list(small = TRUE)))

    for (endo in cell$endos) {
      check_firststage(fit, fixture, endo)
      check_firststage(fit_small, fixture, endo)
    }

    # Stata's e(first) was verified byte-identical under `small` across iid/hc1/cluster variants in the retired fixtures, and this family's shape doesn't fit the generic test_stata_fixture_cells() stat/p/df harness, hence this bespoke loop.
    expect_equal(fit_small$first_stage, fit$first_stage)
  })
}


# ============================================================================
# Fixture-free identity tests
# ============================================================================

test_that("widstat equals first-stage F when K1=1", {
  # H41 widstat=F identity (help.txt:1325), already verified TRUE in the retired card fixtures: with a single endogenous regressor, the weak identification statistic (Cragg-Donald F under iid, KP Wald F under robust/cluster) coincides with the first-stage F statistic.
  fit_iid <- ivreg2(mroz_formula, data = mroz)
  expect_equal(fit_iid$diagnostics$weak_id$stat,
               fit_iid$first_stage$educ$f_stat)

  fit_robust <- ivreg2(mroz_formula, data = mroz, vcov = "robust")
  expect_equal(fit_robust$diagnostics$weak_id_robust$stat,
               fit_robust$first_stage$educ$f_stat)
})

test_that("first stage is estimator-invariant", {
  # Verified in the retired card fixtures that fs_overid_liml_* was byte-identical to fs_overid_iid_*, hence this identity is expected to hold structurally: first-stage regressions don't depend on the second-stage estimator.
  fit_2sls_iid <- ivreg2(mroz_formula, data = mroz)
  fit_liml <- ivreg2(mroz_formula, data = mroz, method = "liml")
  expect_equal(fit_liml$first_stage, fit_2sls_iid$first_stage)

  fit_2sls_robust <- ivreg2(mroz_formula, data = mroz, vcov = "robust")
  fit_gmm2s <- ivreg2(mroz_formula, data = mroz, vcov = "robust",
                      method = "gmm2s")
  expect_equal(fit_gmm2s$first_stage, fit_2sls_robust$first_stage)
})
