# Tests for extractable first-stage model objects (Ticket S1)
# Verifies coefficients, VCV, RMSE against Stata `savefirst` CSV fixtures
# generated by generate-firststage-fixtures.do
#
# M-25 fixture re-base (planning/22-spec-matrix.md): this family moved off
# the Card ad hoc data onto the canonical help-file bases (mroz, griliches76,
# abdata). The retired LIML config is dropped entirely -- estimator-invariance
# of the first-stage object is now covered by the fixture-free identity test
# "first stage is estimator-invariant" in test-diagnostics-firststage.R.

# --- Bundled datasets (lazy-loaded with the package) ---
data(mroz, package = "ivreg2r")
data(griliches, package = "ivreg2r")
data(abdata, package = "ivreg2r")

mroz_formula <- lwage ~ exper + expersq | educ | age + kidslt6 + kidsge6
# mroz_justid_formula comes from helper-fixtures.R.

# gril_formula (H06, help.txt:1154) is now provided by helper-fixtures.R.

# ============================================================================
# Fixture readers
# ============================================================================

skip_if_no_fs_fixtures <- function(prefix, suffixes = c("coef", "vcov", "scalars")) {
  for (s in suffixes) {
    path <- fixture_path(paste0(prefix, "_", s, ".csv"))
    skip_if_not(file.exists(path), "Stata fixture not available")
  }
}

read_fs_coef <- function(prefix) {
  fx <- read.csv(fixture_path(paste0(prefix, "_coef.csv")),
                 strip.white = TRUE)
  vals <- fx$estimate
  nms <- ifelse(fx$term == "_cons", "(Intercept)", fx$term)
  names(vals) <- nms
  vals
}

read_fs_vcov <- function(prefix) {
  read_vcov_fixture(fixture_path(paste0(prefix, "_vcov.csv")))
}

read_fs_scalars <- function(prefix) {
  read_scalar_fixture(fixture_path(paste0(prefix, "_scalars.csv")))
}

# ============================================================================
# Tests: API and structure
# ============================================================================

test_that("first_stage() errors informatively without flag", {
  fit <- ivreg2(mroz_formula, data = mroz)
  expect_error(first_stage(fit), "Re-fit with `first_stage = TRUE`")
})

test_that("first_stage() errors for OLS models", {
  fit_ols <- ivreg2(lwage ~ exper + expersq, data = mroz,
                     first_stage = TRUE)
  expect_error(first_stage(fit_ols), "Re-fit with `first_stage = TRUE`")
})

test_that("first_stage returns correct class and structure", {
  fit <- ivreg2(mroz_formula, data = mroz, first_stage = TRUE)
  fs <- first_stage(fit)
  expect_type(fs, "list")
  expect_named(fs, "educ")
  expect_s3_class(fs$educ, "ivreg2_first_stage")

  expect_length(coef(fs$educ), 6L)
  expect_equal(dim(vcov(fs$educ)), c(6L, 6L))
  expect_length(residuals(fs$educ), fit$nobs)
  expect_length(fitted(fs$educ), fit$nobs)
  expect_equal(nobs(fs$educ), fit$nobs)
})


# ============================================================================
# Tests: Stata parity — coefficients, VCV, scalars
# ============================================================================

test_that("first_stage matches Stata (mroz, IID)", {
  skip_if_no_fs_fixtures("fs_mroz_iid")
  fit <- ivreg2(mroz_formula, data = mroz, first_stage = TRUE)
  fs <- first_stage(fit)$educ

  stata_coef <- read_fs_coef("fs_mroz_iid")
  stata_vcov <- read_fs_vcov("fs_mroz_iid")
  stata_sc <- read_fs_scalars("fs_mroz_iid")

  for (nm in names(stata_coef)) {
    expect_equal(coef(fs)[[nm]], stata_coef[[nm]], tolerance = stata_tol$coef,
                 label = paste0("coef [", nm, "]"))
  }
  expect_vcov_equal(vcov(fs), stata_vcov, tol = stata_tol$vcov)
  expect_equal(fs$sigma, stata_sc$rmse, tolerance = stata_tol$coef)
  expect_equal(fs$df.residual, as.integer(stata_sc$df_r))
})

test_that("first_stage matches Stata (mroz, robust)", {
  skip_if_no_fs_fixtures("fs_mroz_robust", c("vcov", "scalars"))
  fit <- ivreg2(mroz_formula, data = mroz, vcov = "robust",
                first_stage = TRUE)
  fs <- first_stage(fit)$educ

  stata_vcov <- read_fs_vcov("fs_mroz_robust")
  stata_sc <- read_fs_scalars("fs_mroz_robust")

  # No fs_mroz_robust_coef fixture is shipped: the saved first-stage OLS coefficients are VCE-invariant (the robust coef file was verified byte-identical to the iid one at re-base, and the generator's nocoef option skips the duplicate), so the robust fit's coefficients are compared against the iid coef fixture.
  stata_coef <- read_fs_coef("fs_mroz_iid")
  for (nm in names(stata_coef)) {
    expect_equal(coef(fs)[[nm]], stata_coef[[nm]], tolerance = stata_tol$coef,
                 label = paste0("coef [", nm, "]"))
  }
  expect_vcov_equal(vcov(fs), stata_vcov, tol = stata_tol$vcov)
  expect_equal(fs$sigma, stata_sc$rmse, tolerance = stata_tol$coef)
  expect_equal(fs$df.residual, as.integer(stata_sc$df_r))
})

# Restores the saved-equation coverage of the retired just-identified fs_just_robust config (single-excluded-instrument L1=K1=1 equation).
test_that("first_stage matches Stata (mroz just-identified, robust)", {
  skip_if_no_fs_fixtures("fs_mroz_justid_robust")
  fit <- ivreg2(mroz_justid_formula, data = mroz, vcov = "robust",
                first_stage = TRUE)
  fs <- first_stage(fit)$educ

  stata_coef <- read_fs_coef("fs_mroz_justid_robust")
  stata_vcov <- read_fs_vcov("fs_mroz_justid_robust")
  stata_sc <- read_fs_scalars("fs_mroz_justid_robust")

  for (nm in names(stata_coef)) {
    expect_equal(coef(fs)[[nm]], stata_coef[[nm]], tolerance = stata_tol$coef,
                 label = paste0("coef [", nm, "]"))
  }
  expect_vcov_equal(vcov(fs), stata_vcov, tol = stata_tol$vcov)
  expect_equal(fs$sigma, stata_sc$rmse, tolerance = stata_tol$coef)
  expect_equal(fs$df.residual, as.integer(stata_sc$df_r))
})

test_that("first_stage matches Stata (abdata, cluster(id) M=140)", {
  skip_if_no_fs_fixtures("fs_ab_cl")
  fit <- ivreg2(ab_formula, data = abdata, tvar = "year", ivar = "id",
                clusters = ~id, first_stage = TRUE)
  fs <- first_stage(fit)$w

  stata_coef <- read_fs_coef("fs_ab_cl")
  names(stata_coef) <- translate_stata_ts_names(names(stata_coef))
  stata_vcov <- read_fs_vcov("fs_ab_cl")
  dimnames(stata_vcov) <- list(translate_stata_ts_names(rownames(stata_vcov)),
                               translate_stata_ts_names(colnames(stata_vcov)))
  stata_sc <- read_fs_scalars("fs_ab_cl")

  # Scale-aware coefficient bound: |diff| <= stata_tol$coef * max(1, |stata|). All seven coefficients agree with Stata to ~5e-9 ABSOLUTE, inside the suite's normal observed band (investigated at re-base: abdata.rda is bit-identical to the .dta Stata used and cond(Z) ~ 24, so this is ordinary cross-implementation noise, not a formula bug). d(k, 1)'s coefficient is near-zero (~2.8e-4), so a plain relative tolerance would inflate that ordinary gap to ~1.7e-5 and fail; the max(1, .) floor keeps O(1) coefficients at the standard 1e-6 relative check while bounding the near-zero one at 1e-6 absolute (~200x margin over the observed gap in both regimes).
  for (nm in names(stata_coef)) {
    expect_lt(abs(coef(fs)[[nm]] - stata_coef[[nm]]),
              stata_tol$coef * max(1, abs(stata_coef[[nm]])),
              label = paste0("coef [", nm, "] |R - Stata|"))
  }
  expect_vcov_equal(vcov(fs), stata_vcov, tol = stata_tol$vcov)
  expect_equal(fs$sigma, stata_sc$rmse, tolerance = stata_tol$coef)
  # Stata stores df_r = N-L-dofminus-sdofminus even for clustered models,
  # but its display engine caps at M-1. Our df.residual = M-1 for clustered.
  expect_equal(fs$df.residual, as.integer(stata_sc$N_clust) - 1L)
  expect_equal(fs$n_clusters, as.integer(stata_sc$N_clust))
})

test_that("first_stage matches Stata (griliches aweight, IID)", {
  skip_if_no_fs_fixtures("fs_gril_aw_iid")
  fit <- ivreg2(gril_formula, data = griliches_awt, weights = awt,
                first_stage = TRUE)
  fs <- first_stage(fit)$iq

  stata_coef <- read_fs_coef("fs_gril_aw_iid")
  names(stata_coef) <- translate_stata_xi_names(names(stata_coef))
  stata_vcov <- read_fs_vcov("fs_gril_aw_iid")
  dimnames(stata_vcov) <- list(translate_stata_xi_names(rownames(stata_vcov)),
                               translate_stata_xi_names(colnames(stata_vcov)))
  stata_sc <- read_fs_scalars("fs_gril_aw_iid")

  for (nm in names(stata_coef)) {
    expect_equal(coef(fs)[[nm]], stata_coef[[nm]], tolerance = stata_tol$coef,
                 label = paste0("coef [", nm, "]"))
  }
  expect_vcov_equal(vcov(fs), stata_vcov, tol = stata_tol$vcov)
  expect_equal(fs$sigma, stata_sc$rmse, tolerance = stata_tol$coef)
})

test_that("first_stage matches Stata (griliches aweight, robust)", {
  skip_if_no_fs_fixtures("fs_gril_aw_robust", c("vcov", "scalars"))
  fit <- ivreg2(gril_formula, data = griliches_awt, weights = awt,
                vcov = "robust", first_stage = TRUE)
  fs <- first_stage(fit)$iq

  stata_vcov <- read_fs_vcov("fs_gril_aw_robust")
  dimnames(stata_vcov) <- list(translate_stata_xi_names(rownames(stata_vcov)),
                               translate_stata_xi_names(colnames(stata_vcov)))
  stata_sc <- read_fs_scalars("fs_gril_aw_robust")

  # No fs_gril_aw_robust_coef fixture is shipped (VCE-invariant first-stage coefficients; see the mroz robust cell note) — compare against the iid coef fixture.
  stata_coef <- read_fs_coef("fs_gril_aw_iid")
  names(stata_coef) <- translate_stata_xi_names(names(stata_coef))
  for (nm in names(stata_coef)) {
    expect_equal(coef(fs)[[nm]], stata_coef[[nm]], tolerance = stata_tol$coef,
                 label = paste0("coef [", nm, "]"))
  }
  expect_vcov_equal(vcov(fs), stata_vcov, tol = stata_tol$vcov)
  expect_equal(fs$sigma, stata_sc$rmse, tolerance = stata_tol$coef)
})


# ============================================================================
# Tests: broom methods
# ============================================================================

test_that("tidy() and glance() work for first-stage objects", {
  fit <- ivreg2(mroz_formula, data = mroz, vcov = "robust",
                first_stage = TRUE)
  fs <- first_stage(fit)$educ

  td <- tidy(fs)
  expect_s3_class(td, "tbl_df")
  expect_equal(nrow(td), 6L)
  expect_true(all(c("term", "estimate", "std.error", "statistic", "p.value",
                     "conf.low", "conf.high") %in% names(td)))

  gl <- glance(fs)
  expect_s3_class(gl, "tbl_df")
  expect_equal(nrow(gl), 1L)
  expect_true("sigma" %in% names(gl))
  expect_true("f_stat" %in% names(gl))
  expect_true("partial_r2" %in% names(gl))
})

test_that("tidy(exponentiate = TRUE) works for first-stage objects", {
  fit <- ivreg2(mroz_formula, data = mroz, first_stage = TRUE)
  fs <- first_stage(fit)$educ

  td_raw <- tidy(fs, conf.int = TRUE)
  td_exp <- tidy(fs, conf.int = TRUE, exponentiate = TRUE)
  expect_equal(td_exp$estimate, exp(td_raw$estimate))
  expect_equal(td_exp$conf.low, exp(td_raw$conf.low))
  expect_equal(td_exp$conf.high, exp(td_raw$conf.high))
  expect_equal(td_exp$std.error, td_raw$std.error)
})


# ============================================================================
# Tests: print and summary
# ============================================================================

test_that("summary() and print() work for first-stage objects", {
  fit <- ivreg2(mroz_formula, data = mroz, first_stage = TRUE)
  fs <- first_stage(fit)$educ

  s <- summary(fs)
  expect_s3_class(s, "summary.ivreg2_first_stage")

  out <- capture.output(print(s))
  expect_true(any(grepl("First-stage regression", out)))
  expect_true(any(grepl("Root MSE", out)))

  out2 <- capture.output(print(fs))
  expect_true(any(grepl("First-stage regression", out2)))
})

test_that("confint() works for first-stage objects", {
  fit <- ivreg2(mroz_formula, data = mroz, first_stage = TRUE)
  fs <- first_stage(fit)$educ

  ci <- confint(fs)
  expect_equal(nrow(ci), 6L)
  expect_equal(ncol(ci), 2L)

  ci2 <- confint(fs, parm = "kidslt6")
  expect_equal(nrow(ci2), 1L)
})


# ============================================================================
# Tests: Codex review bug fixes
# ============================================================================

test_that("clustered first-stage df.residual is M-1, not N-L", {
  fit <- ivreg2(ab_formula, data = abdata, tvar = "year", ivar = "id",
                clusters = ~id, first_stage = TRUE)
  fs <- first_stage(fit)$w

  # M=140 clusters on id, so df.residual should be M-1 = 139
  expect_equal(fs$df.residual, 139L)

  # summary/tidy/confint should use df=139, not the raw residual df
  s <- summary(fs)
  p_from_summary <- s$coef_table["(Intercept)", "Pr(>|t|)"]
  p_if_wrong_df <- 2 * pt(-abs(s$coef_table["(Intercept)", "t value"]),
                           df = fit$nobs)
  expect_true(p_from_summary > p_if_wrong_df)

  # confint should be wider with df=139 than with the raw residual df
  ci <- confint(fs, parm = "(Intercept)")
  ci_width <- ci[1, 2] - ci[1, 1]
  crit_wrong <- qt(0.025, df = fit$nobs)
  se_intercept <- sqrt(vcov(fs)["(Intercept)", "(Intercept)"])
  width_wrong <- -2 * crit_wrong * se_intercept
  expect_true(ci_width > width_wrong)
})

test_that("HAC first-stage residuals are in original row order", {
  data(phillips, package = "ivreg2r")
  # Deliberately shuffle row order so sorted != original
  set.seed(42)
  phillips_shuffled <- phillips[sample(nrow(phillips)), ]

  fit <- ivreg2(cinf ~ unem | inf_1 | inf_2,
                data = phillips_shuffled, vcov = "HAC",
                kernel = "bartlett", bw = 3,
                tvar = "year",
                first_stage = TRUE)
  fs <- first_stage(fit)$inf_1

  # First-stage residuals + fitted should sum to the endogenous variable
  # in the correct (shuffled) row order. Use the model frame to get the
  # observations actually used (after NA removal).
  mf <- model.frame(fit)
  inf1_used <- mf$inf_1
  recon <- unname(fitted(fs) + residuals(fs))
  expect_equal(recon, inf1_used, tolerance = 1e-10)

  # Also verify alignment with main model residuals (both should be
  # in original row order)
  expect_equal(length(residuals(fs)), length(residuals(fit)))
})


# ============================================================================
# Tests: no regressions
# ============================================================================

test_that("first_stage = FALSE (default) doesn't change existing behavior", {
  fit1 <- ivreg2(mroz_formula, data = mroz)
  fit2 <- ivreg2(mroz_formula, data = mroz, first_stage = TRUE)

  expect_equal(coef(fit1), coef(fit2))
  expect_equal(vcov(fit1), vcov(fit2))
  expect_equal(fit1$sigma, fit2$sigma)
  expect_equal(fit1$first_stage, fit2$first_stage)
})
