# ============================================================================
# Tests: Two-way cluster-robust VCV (Ticket I1)
# ============================================================================
#
# Family M-14 (re-based 2026-07-05 per Frank's ruling): IV x two-way cluster
# Stata parity on the cigar cells (Baltagi-Levin demand spec, D5a -- no
# upstream IV+two-way worked example exists in the project's data stable).
# OLS two-way cluster parity is owned by the hf suite (nlswork H104/H105).
# The retired sim_twoway family's known-dirty weighted gate (Hansen J
# suppressed under a rank-deficient S matrix) was an artifact of that
# family's non-reproducible synthetic draw, not a property of two-way
# clustering itself -- the cigar weighted cell here is expected-clean and
# is asserted clean below.
#
# Cameron-Gelbach-Miller (2006) two-way clustering:
# V_twoway = V_c1 + V_c2 - V_intersection
# Effective cluster count M = min(M1, M2) per Stata convention.
#
# Generated by (per-cell options noted):
#   ivreg2 lsales lrndi (lrprice = lrpimin l.lrprice), cluster(state year)
#     first endog(lrprice)
#   cl2_small adds `small`; cl2_wt adds `[aw=cwt]` with cwt = mod(state,4)+1;
#   cl2_dof adds `dofminus(2) sdofminus(1)`.

# cigar_formula and cigar_real (log-transformed regressors plus the
# deterministic two-way aweight cwt) are shared objects in
# helper-fixtures.R, next to klein_formula/ab_formula/card_wt.

# Shared fits (M-17 hoisting precedent): each configuration is fit once here
# and reused across the parity, metadata, and property sections below.
fit_cl2       <- ivreg2(cigar_formula, data = cigar_real, tvar = "year",
                         ivar = "state", clusters = ~state + year,
                         endog = "lrprice")
fit_cl2_small <- ivreg2(cigar_formula, data = cigar_real, tvar = "year",
                         ivar = "state", clusters = ~state + year,
                         endog = "lrprice", small = TRUE)
fit_cl2_wt    <- ivreg2(cigar_formula, data = cigar_real, tvar = "year",
                         ivar = "state", clusters = ~state + year,
                         endog = "lrprice", weights = cwt)
fit_cl2_dof   <- ivreg2(cigar_formula, data = cigar_real, tvar = "year",
                         ivar = "state", clusters = ~state + year,
                         endog = "lrprice", dofminus = 2L, sdofminus = 1L)
fit_cl1       <- ivreg2(cigar_formula, data = cigar_real, tvar = "year",
                         ivar = "state", clusters = ~state,
                         endog = "lrprice")
fit_iid       <- ivreg2(cigar_formula, data = cigar_real, tvar = "year",
                         ivar = "state", endog = "lrprice")
fit_hc1       <- ivreg2(cigar_formula, data = cigar_real, tvar = "year",
                         ivar = "state", vcov = "robust", endog = "lrprice")


# ============================================================================
# Section 1: Stata parity -- coefficients, VCV, SEs (cl2)
# ============================================================================

test_that("2SLS two-way cluster VCV matches Stata cigar cl2 fixture", {
  skip_if(!file.exists(fixture_path("cigar_vcov_cl2.csv")), "VCV fixture not found")
  expect_vcov_fixture(fit_cl2, "cigar_vcov_cl2.csv")
})

test_that("2SLS two-way cluster coef/SE match Stata cigar cl2 fixture", {
  skip_if(!file.exists(fixture_path("cigar_coef_cl2.csv")), "Coef fixture not found")
  expect_coef_fixture(fit_cl2, "cigar_coef_cl2.csv")
})


# ============================================================================
# Section 2: Stata parity -- VCV and SEs (cl2_small)
# ============================================================================

test_that("2SLS two-way cluster VCV matches Stata cigar cl2_small fixture", {
  skip_if(!file.exists(fixture_path("cigar_vcov_cl2_small.csv")), "VCV fixture not found")
  expect_vcov_fixture(fit_cl2_small, "cigar_vcov_cl2_small.csv")
})

test_that("2SLS two-way cluster coef/SE match Stata cigar cl2_small fixture", {
  skip_if(!file.exists(fixture_path("cigar_coef_cl2_small.csv")), "Coef fixture not found")
  expect_coef_fixture(fit_cl2_small, "cigar_coef_cl2_small.csv")
})


# ============================================================================
# Section 3: Stata parity -- VCV and SEs (cl2_wt, cl2_dof)
# ============================================================================

test_that("weighted 2SLS two-way cluster VCV matches Stata cigar cl2_wt fixture", {
  skip_if(!file.exists(fixture_path("cigar_vcov_cl2_wt.csv")), "VCV fixture not found")
  expect_vcov_fixture(fit_cl2_wt, "cigar_vcov_cl2_wt.csv")
})

test_that("weighted 2SLS two-way cluster coef/SE match Stata cigar cl2_wt fixture", {
  skip_if(!file.exists(fixture_path("cigar_coef_cl2_wt.csv")), "Coef fixture not found")
  expect_coef_fixture(fit_cl2_wt, "cigar_coef_cl2_wt.csv")
})

test_that("two-way cluster with dofminus VCV matches Stata cigar cl2_dof fixture", {
  skip_if(!file.exists(fixture_path("cigar_vcov_cl2_dof.csv")), "VCV fixture not found")
  expect_vcov_fixture(fit_cl2_dof, "cigar_vcov_cl2_dof.csv")
})

test_that("two-way cluster with dofminus coef/SE match Stata cigar cl2_dof fixture", {
  skip_if(!file.exists(fixture_path("cigar_coef_cl2_dof.csv")), "Coef fixture not found")
  expect_coef_fixture(fit_cl2_dof, "cigar_coef_cl2_dof.csv")
})


# ============================================================================
# Section 4: Stata parity -- diagnostics (cl2, cl2_small, cl2_wt, cl2_dof)
# ============================================================================

test_that("two-way cluster diagnostics match Stata cigar cl2 fixture", {
  diag_path <- fixture_path("cigar_diagnostics_cl2.csv")
  skip_if(!file.exists(diag_path), "Diagnostics fixture not found")

  stata <- read_diagnostics(diag_path)

  # Hansen J
  expect_equal(fit_cl2$diagnostics$overid$stat, stata$j,
               tolerance = stata_tol$stat, info = "Hansen J stat")
  expect_equal(fit_cl2$diagnostics$overid$p, stata$jp,
               tolerance = stata_tol$pval, info = "Hansen J p")

  # KP rk LM (underidentification)
  expect_equal(fit_cl2$diagnostics$underid$stat, stata$idstat,
               tolerance = stata_tol$stat, info = "KP rk LM stat")
  expect_equal(fit_cl2$diagnostics$underid$p, stata$idp,
               tolerance = stata_tol$pval, info = "KP rk LM p")

  # KP rk Wald F (weak identification, robust)
  expect_equal(fit_cl2$diagnostics$weak_id_robust$stat, stata$widstat,
               tolerance = stata_tol$stat, info = "KP rk Wald F")

  # Anderson-Rubin
  expect_equal(fit_cl2$diagnostics$anderson_rubin$f_stat, stata$arf,
               tolerance = stata_tol$stat, info = "AR F stat")
  expect_equal(fit_cl2$diagnostics$anderson_rubin$f_p, stata$arfp,
               tolerance = stata_tol$pval, info = "AR F p")
  expect_equal(fit_cl2$diagnostics$anderson_rubin$chi2_stat, stata$archi2,
               tolerance = stata_tol$stat, info = "AR chi2 stat")
  expect_equal(fit_cl2$diagnostics$anderson_rubin$chi2_p, stata$archi2p,
               tolerance = stata_tol$pval, info = "AR chi2 p")

  # Stock-Wright S
  expect_equal(fit_cl2$diagnostics$stock_wright$stat, stata$sstat,
               tolerance = stata_tol$stat, info = "Stock-Wright S stat")
  expect_equal(fit_cl2$diagnostics$stock_wright$p, stata$sstatp,
               tolerance = stata_tol$pval, info = "Stock-Wright S p")

  # Endogeneity test
  expect_equal(fit_cl2$diagnostics$endogeneity$stat, stata$estat,
               tolerance = stata_tol$stat, info = "Endogeneity stat")
  expect_equal(fit_cl2$diagnostics$endogeneity$p, stata$estatp,
               tolerance = stata_tol$pval, info = "Endogeneity p")

  # Model F
  expect_equal(fit_cl2$model_f, stata$F_stat,
               tolerance = stata_tol$stat, info = "Model F stat")
  expect_equal(fit_cl2$model_f_p, stata$F_p,
               tolerance = stata_tol$pval, info = "Model F p")
})

test_that("two-way cluster diagnostics match Stata cigar cl2_small fixture", {
  diag_path <- fixture_path("cigar_diagnostics_cl2_small.csv")
  skip_if(!file.exists(diag_path), "Diagnostics fixture not found")

  stata <- read_diagnostics(diag_path)

  # Model F (small)
  expect_equal(fit_cl2_small$model_f, stata$F_stat,
               tolerance = stata_tol$stat, info = "Model F stat (small)")
  expect_equal(fit_cl2_small$model_f_p, stata$F_p,
               tolerance = stata_tol$pval, info = "Model F p (small)")

  # N_clust
  expect_equal(as.integer(stata$N_clust), fit_cl2_small$n_clusters,
               info = "N_clust")
})

test_that("weighted two-way cluster diagnostics match Stata cigar cl2_wt fixture (clean)", {
  diag_path <- fixture_path("cigar_diagnostics_cl2_wt.csv")
  skip_if(!file.exists(diag_path), "Diagnostics fixture not found")

  stata <- read_diagnostics(diag_path)

  # Unlike the retired sim_twoway synthetic weighted cell, the cigar weighted
  # cell is not rank-deficient: Stata reports a full Hansen J here, and so
  # do we -- no warning, no suppression.
  expect_equal(fit_cl2_wt$diagnostics$overid$stat, stata$j,
               tolerance = stata_tol$stat, info = "Hansen J stat (weighted)")
  expect_equal(fit_cl2_wt$diagnostics$overid$p, stata$jp,
               tolerance = stata_tol$pval, info = "Hansen J p (weighted)")

  expect_equal(fit_cl2_wt$model_f, stata$F_stat,
               tolerance = stata_tol$stat, info = "Model F (weighted)")
  expect_equal(fit_cl2_wt$model_f_p, stata$F_p,
               tolerance = stata_tol$pval, info = "Model F p (weighted)")
})

test_that("two-way cluster dofminus diagnostics match Stata cigar cl2_dof fixture", {
  diag_path <- fixture_path("cigar_diagnostics_cl2_dof.csv")
  skip_if(!file.exists(diag_path), "Diagnostics fixture not found")

  stata <- read_diagnostics(diag_path)

  expect_equal(fit_cl2_dof$diagnostics$overid$stat, stata$j,
               tolerance = stata_tol$stat, info = "Hansen J (dofminus)")
  expect_equal(fit_cl2_dof$diagnostics$underid$stat, stata$idstat,
               tolerance = stata_tol$stat, info = "KP rk LM (dofminus)")
  expect_equal(fit_cl2_dof$model_f, stata$F_stat,
               tolerance = stata_tol$stat, info = "Model F (dofminus)")
  expect_equal(fit_cl2_dof$diagnostics$endogeneity$stat, stata$estat,
               tolerance = stata_tol$stat, info = "Endogeneity stat (dofminus)")
  expect_equal(fit_cl2_dof$diagnostics$endogeneity$p, stata$estatp,
               tolerance = stata_tol$pval, info = "Endogeneity p (dofminus)")
})


# ============================================================================
# Section 5: Stata parity -- first-stage F
# ============================================================================

test_that("two-way cluster first-stage F matches Stata cigar cl2 fixture", {
  fs_path <- fixture_path("cigar_firststage_cl2.csv")
  skip_if(!file.exists(fs_path), "First-stage fixture not found")

  stata_fs <- read_firststage(fs_path)
  stata_f <- get_fs_value(stata_fs, "F", "lrprice")
  expect_equal(fit_cl2$first_stage$lrprice$f_stat, stata_f,
               tolerance = stata_tol$stat, info = "First-stage F")
})


# ============================================================================
# Section 6: Metadata
# ============================================================================

# Pinned to Stata's own per-dimension cluster counts (N_clust1/N_clust2 in
# the cl2 diagnostics fixture) rather than bare literals, so a bug that
# swaps or miscounts either dimension is caught against ground truth instead
# of against a hand-copied number.
test_that("n_clusters1/n_clusters2 match Stata's N_clust1/N_clust2 for two-way clustering", {
  diag_path <- fixture_path("cigar_diagnostics_cl2.csv")
  skip_if(!file.exists(diag_path), "Diagnostics fixture not found")
  dx <- read_diagnostics(diag_path)
  expect_identical(fit_cl2$n_clusters1, as.integer(dx$N_clust1))
  expect_identical(fit_cl2$n_clusters2, as.integer(dx$N_clust2))
  expect_identical(fit_cl2$n_clusters, min(fit_cl2$n_clusters1, fit_cl2$n_clusters2))
})

test_that("df.residual = M - 1 for two-way clustering", {
  expect_identical(fit_cl2$df.residual, fit_cl2$n_clusters - 1L)
})

test_that("vcov_type is 'CL' when two-way clustered", {
  expect_identical(fit_cl2$vcov_type, "CL")
})

test_that("cluster_var stores both variable names for two-way", {
  expect_identical(fit_cl2$cluster_var, c("state", "year"))
})

test_that("n_clusters1 and n_clusters2 are NULL for one-way clustering", {
  expect_null(fit_cl1$n_clusters1)
  expect_null(fit_cl1$n_clusters2)
})

test_that("glance includes n_clusters1 and n_clusters2", {
  gl <- glance(fit_cl2)
  expect_true("n_clusters1" %in% names(gl))
  expect_true("n_clusters2" %in% names(gl))
  expect_equal(gl$n_clusters1, fit_cl2$n_clusters1)
  expect_equal(gl$n_clusters2, fit_cl2$n_clusters2)
})


# ============================================================================
# Section 7: Properties
# ============================================================================

test_that("two-way cluster VCV is symmetric", {
  expect_equal(fit_cl2$vcov, t(fit_cl2$vcov),
               tolerance = .Machine$double.eps^0.5)
})

test_that("coefficients are identical across iid / HC1 / one-way CL / two-way CL", {
  expect_equal(coef(fit_hc1), coef(fit_iid),
               tolerance = .Machine$double.eps^0.5)
  expect_equal(coef(fit_cl1), coef(fit_iid),
               tolerance = .Machine$double.eps^0.5)
  expect_equal(coef(fit_cl2), coef(fit_iid),
               tolerance = .Machine$double.eps^0.5)
})

test_that("two-way cluster VCV differs from one-way cluster VCV", {
  expect_false(isTRUE(all.equal(fit_cl1$vcov, fit_cl2$vcov)))
})

# NEW test (M-14 re-base): the one-way sibling test-vcov-cluster.R already
# asserts this correction-factor identity for one-way clustering; the old
# sim_twoway file never carried the two-way analogue. Break-it-once verified
# (see the M-14 re-base report): perturbing the correction to use N (not
# N - 1) in the numerator flips this from pass to a reported ~0.08% mismatch.
test_that("small=TRUE two-way cluster VCV equals small=FALSE times correction factor", {
  N <- fit_cl2$nobs
  K <- length(coef(fit_cl2))
  M <- fit_cl2$n_clusters
  correction <- ((N - 1) / (N - K)) * (M / (M - 1))
  expect_equal(fit_cl2_small$vcov, fit_cl2$vcov * correction,
               tolerance = .Machine$double.eps^0.5)
})

# NEW test (code-review fix): restores the OLS x two-way x small intersection
# retired with the sim_twoway cl2_ols_small cell -- OLS parity itself is
# hf-owned (H104), and the small correction has no OLS/IV branch, so this
# identity pins the OLS-side dof bookkeeping without duplicating Stata parity
# coverage. Mirrors the IV variant directly above.
test_that("OLS: small=TRUE two-way cluster VCV equals small=FALSE times correction factor", {
  fit_no <- ivreg2(lsales ~ lrndi + lrprice, data = cigar_real,
                    tvar = "year", ivar = "state", clusters = ~state + year)
  fit_sm <- ivreg2(lsales ~ lrndi + lrprice, data = cigar_real,
                    tvar = "year", ivar = "state", clusters = ~state + year,
                    small = TRUE)
  N <- fit_no$nobs
  K <- length(coef(fit_no))
  M <- min(fit_no$n_clusters1, fit_no$n_clusters2)
  correction <- ((N - 1) / (N - K)) * (M / (M - 1))
  expect_equal(fit_sm$vcov, fit_no$vcov * correction,
               tolerance = .Machine$double.eps^0.5)
})


# ============================================================================
# Section 8: Input validation
# ============================================================================

test_that("3+ cluster variables gives error", {
  expect_error(
    ivreg2(mpg ~ wt + hp, data = mtcars, clusters = ~ cyl + gear + carb),
    "one or two variables"
  )
})

test_that("missing second cluster variable gives error", {
  expect_error(
    ivreg2(mpg ~ wt + hp, data = mtcars, clusters = ~ cyl + nonexistent),
    "not found in data"
  )
})

test_that("NA in second cluster variable gives error", {
  df <- mtcars
  df$clust2 <- c(NA, rep(1:3, length.out = nrow(df) - 1))
  expect_error(
    ivreg2(mpg ~ wt + hp, data = df, clusters = ~ cyl + clust2),
    "contains NA"
  )
})

test_that("single-level second cluster variable gives error", {
  df <- mtcars
  df$const <- 1
  expect_error(
    ivreg2(mpg ~ wt + hp, data = df, clusters = ~ cyl + const),
    "At least 2 clusters"
  )
})

test_that("interaction operator in clusters formula gives error", {
  expect_error(
    ivreg2(mpg ~ wt + hp, data = mtcars, clusters = ~ cyl:gear),
    "not `:` or `\\*`"
  )
})

test_that("star operator in clusters formula gives error", {
  expect_error(
    ivreg2(mpg ~ wt + hp, data = mtcars, clusters = ~ cyl * gear),
    "not `:` or `\\*`"
  )
})
