# ============================================================================
# Tests: Instrument Redundancy Test (Ticket P1)
# ============================================================================
#
# Tests H0: specified excluded instruments are redundant (zero explanatory power for endogenous regressors) conditional on maintained instruments. KP rk LM test of H0: rank=0. Verifies against Stata ivreg2 fixtures (e(redstat), e(redp), e(reddf)).
#
# M-23 fixture re-base (planning/22-spec-matrix.md): this family moved off the Card/sim_multi_endo/ts_hac ad hoc data onto the canonical help-file bases (griliches76, abdata, phillips), generated by tests/stata-benchmarks/generate-redundancy-fixtures.do. `small` is NOT varied in the fixtures themselves — Stata's e(redstat)/e(redp)/e(reddf) are invariant to `small` (see that .do file's header) — so every fixture-comparison cell below fits both small = FALSE and small = TRUE against the same fixture and additionally asserts the two fits agree to machine precision.

# --- Bundled datasets (lazy-loaded with the package) ---
data(griliches, package = "ivreg2r")
data(abdata, package = "ivreg2r")
data(phillips, package = "ivreg2r")
data(mroz, package = "ivreg2r")

gril_formula <- lw ~ s + expr + tenure + rns + smsa + factor(year) |
  iq | age + mrt

phil_formula <- cinf ~ 1 | unem | l(unem, 1:3)


# ============================================================================
# Structural tests (no fixtures) — griliches base model
# ============================================================================

test_that("redundancy is NULL when not requested", {
  fit <- ivreg2(gril_formula, data = griliches)
  expect_null(fit$diagnostics$redundancy)
})

test_that("redundant = character(0) is silently skipped", {
  fit <- ivreg2(gril_formula, data = griliches, redundant = character(0))
  expect_null(fit$diagnostics$redundancy)
})

test_that("redundancy is NULL for OLS models", {
  fit <- ivreg2(mpg ~ wt + hp, data = mtcars, redundant = "wt")
  expect_null(fit$diagnostics)
})

test_that("redundancy has all expected fields", {
  fit <- ivreg2(gril_formula, data = griliches, redundant = "mrt")
  red <- fit$diagnostics$redundancy
  expect_type(red, "list")
  expect_named(red, c("stat", "p", "df", "test_name", "tested_vars"),
               ignore.order = TRUE)
  expect_equal(red$tested_vars, "mrt")
  expect_identical(red$df, 1L)
  expect_equal(red$test_name, "Redundancy test (LM)")
})

test_that("invalid redundant variable name produces error", {
  expect_error(
    ivreg2(gril_formula, data = griliches, redundant = "not_a_var"),
    "not in the excluded instrument list"
  )
})

test_that("redundant rejects exogenous variable", {
  expect_error(
    ivreg2(gril_formula, data = griliches, redundant = "expr"),
    "not in the excluded instrument list"
  )
})

test_that("redundant rejects endogenous variable", {
  expect_error(
    ivreg2(gril_formula, data = griliches, redundant = "iq"),
    "not in the excluded instrument list"
  )
})

test_that("redundant must be character or NULL", {
  expect_error(
    ivreg2(gril_formula, data = griliches, redundant = 1),
    "character vector or NULL"
  )
})

test_that("duplicate redundant entries are deduplicated with warning", {
  fit_single <- ivreg2(gril_formula, data = griliches, redundant = "mrt")
  expect_warning(
    fit_dup <- ivreg2(gril_formula, data = griliches,
                      redundant = c("mrt", "mrt")),
    "duplicate entries"
  )
  expect_equal(fit_dup$diagnostics$redundancy$stat,
               fit_single$diagnostics$redundancy$stat)
  expect_equal(fit_dup$diagnostics$redundancy$df,
               fit_single$diagnostics$redundancy$df)
})

test_that("redundancy appears in glance output", {
  fit <- ivreg2(gril_formula, data = griliches, redundant = "mrt")
  g <- glance(fit)
  expect_true("redundancy_stat" %in% names(g))
  expect_true("redundancy_p" %in% names(g))
  expect_false(is.na(g$redundancy_stat))
  expect_false(is.na(g$redundancy_p))
})

test_that("redundancy is NA in glance when not requested", {
  fit <- ivreg2(gril_formula, data = griliches)
  g <- glance(fit)
  expect_true(is.na(g$redundancy_stat))
  expect_true(is.na(g$redundancy_p))
})


# ============================================================================
# Property tests
# ============================================================================

test_that("redundancy stat is non-negative", {
  fit <- ivreg2(gril_formula, data = griliches, redundant = "mrt")
  expect_gte(fit$diagnostics$redundancy$stat, 0)
})

test_that("df = K1 * L_tested", {
  # K1=1, L_tested=1 -> df=1
  fit1 <- ivreg2(gril_formula, data = griliches, redundant = "mrt")
  expect_identical(fit1$diagnostics$redundancy$df, 1L)

  # K1=1, L_tested=2 -> df=2
  fit2 <- ivreg2(gril_formula, data = griliches, redundant = c("age", "mrt"))
  expect_identical(fit2$diagnostics$redundancy$df, 2L)
})

test_that("df = K1 * L_tested for multi-endo models", {
  # Inline synthetic dataset (replaces the retired sim_multi_endo fixture data): 2 endogenous regressors, 4 excluded instruments, same shape as the retired test.
  set.seed(20260722)
  n <- 500
  x1 <- rnorm(n)
  x2 <- rnorm(n)
  z1 <- rnorm(n)
  z2 <- rnorm(n)
  z3 <- rnorm(n)
  z4 <- rnorm(n)
  u <- rnorm(n)
  v1 <- rnorm(n)
  v2 <- rnorm(n)
  endo1 <- 0.5 * z1 + 0.3 * z2 + 0.2 * x1 + 0.8 * v1 + 0.3 * u
  endo2 <- 0.4 * z2 + 0.3 * z3 + 0.2 * z4 + 0.1 * x2 + 0.7 * v2 + 0.2 * u
  y <- 1.0 + 0.5 * x1 - 0.3 * x2 + 1.2 * endo1 - 0.8 * endo2 + u
  sim_multi_endo <- data.frame(y, x1, x2, endo1, endo2, z1, z2, z3, z4)

  # K1=2, L_tested=1 -> df=2
  fit1 <- ivreg2(y ~ x1 + x2 | endo1 + endo2 | z1 + z2 + z3 + z4,
                 data = sim_multi_endo, redundant = "z1")
  expect_identical(fit1$diagnostics$redundancy$df, 2L)

  # K1=2, L_tested=2 -> df=4
  fit2 <- ivreg2(y ~ x1 + x2 | endo1 + endo2 | z1 + z2 + z3 + z4,
                 data = sim_multi_endo, redundant = c("z1", "z2"))
  expect_identical(fit2$diagnostics$redundancy$df, 4L)
})

test_that("redundancy suppressed by b0 (no diagnostics)", {
  fit0 <- ivreg2(gril_formula, data = griliches)
  fit <- ivreg2(gril_formula, data = griliches, redundant = "mrt",
                b0 = rep(0, length(coef(fit0))))
  # b0 suppresses all identification diagnostics
  expect_null(fit$diagnostics$redundancy)
})


# ============================================================================
# Fixture comparisons
# ============================================================================
#
# compare_redundancy() makes plain assertions (no test_that) so each cell below is one test_that block that skips cleanly if its fixture is missing, reads the fixture once, and fits the model only when the fixture exists — matching the structure of the other re-based families (see test-diagnostics-orthog.R).

compare_redundancy <- function(fit, fixture) {
  red <- fit$diagnostics$redundancy
  expect_false(is.null(red))
  expect_equal(red$stat, fixture$redstat, tolerance = stata_tol$stat)
  expect_equal(red$p, fixture$redp, tolerance = stata_tol$pval)
  expect_identical(red$df, as.integer(fixture$reddf))
}

redundancy_cells <- list(
  list(name = "gril_red mrt robust (BSS p. 493 anchor)",
       fixture = "gril_red_redundancy_mrt_robust.csv",
       fit_args = list(gril_formula, data = griliches, vcov = "robust",
                       redundant = "mrt")),
  list(name = "gril_red mrt iid",
       fixture = "gril_red_redundancy_mrt_iid.csv",
       fit_args = list(gril_formula, data = griliches, redundant = "mrt")),
  list(name = "gril_red both iid",
       fixture = "gril_red_redundancy_both_iid.csv",
       fit_args = list(gril_formula, data = griliches,
                       redundant = c("age", "mrt"))),
  list(name = "gril_red_dof mrt iid",
       fixture = "gril_red_dof_redundancy_mrt_iid.csv",
       fit_args = list(gril_formula, data = griliches,
                       redundant = "mrt", dofminus = 1L)),
  list(name = "gril_red_dof mrt robust",
       fixture = "gril_red_dof_redundancy_mrt_robust.csv",
       fit_args = list(gril_formula, data = griliches, vcov = "robust",
                       redundant = "mrt", dofminus = 1L)),
  list(name = "gril_red_aw mrt iid (aweight)",
       fixture = "gril_red_aw_redundancy_mrt_iid.csv",
       fit_args = list(gril_formula, data = griliches_awt,
                       redundant = "mrt", weights = quote(awt))),
  list(name = "ab_red d2ys iid",
       fixture = "ab_red_redundancy_d2ys_iid.csv",
       fit_args = list(ab_formula, data = abdata, tvar = "year",
                       ivar = "id", redundant = "d(ys, 2)")),
  list(name = "ab_red d2ys robust (K1=3 x HC)",
       fixture = "ab_red_redundancy_d2ys_robust.csv",
       fit_args = list(ab_formula, data = abdata, tvar = "year",
                       ivar = "id", vcov = "robust", redundant = "d(ys, 2)")),
  list(name = "ab_red d2k+d2ys iid (K1=3 x L_tested=2, df=6)",
       fixture = "ab_red_redundancy_d2kd2ys_iid.csv",
       fit_args = list(ab_formula, data = abdata, tvar = "year",
                       ivar = "id", redundant = c("d(k, 2)", "d(ys, 2)"))),
  list(name = "ab_red d2ys cl",
       fixture = "ab_red_redundancy_d2ys_cl.csv",
       fit_args = list(ab_formula, data = abdata, tvar = "year",
                       ivar = "id", clusters = ~id, redundant = "d(ys, 2)")),
  # Stata ignores dofminus in the cluster-VCE redundancy stat (verified byte-identical at re-base), so the dofminus fit is pinned against the SAME d2ys_cl fixture rather than a duplicate file.
  list(name = "ab_red d2ys cl + dofminus (dofminus ignored under cluster VCE)",
       fixture = "ab_red_redundancy_d2ys_cl.csv",
       fit_args = list(ab_formula, data = abdata, tvar = "year",
                       ivar = "id", clusters = ~id, redundant = "d(ys, 2)",
                       dofminus = 1L)),
  list(name = "phil_red l3 bartlett bw3 (HAC)",
       fixture = "phil_red_redundancy_l3_bartlett_bw3.csv",
       fit_args = list(phil_formula, data = phillips, tvar = "year",
                       vcov = "HAC", kernel = "Bartlett", bw = 3,
                       redundant = "l(unem, 3)"))
)

test_stata_fixture_cells(redundancy_cells, compare_redundancy,
                         slot = "redundancy",
                         label_prefix = "redundancy matches Stata")


# ============================================================================
# Fixture-free identity tests
# ============================================================================

test_that("gmm2s redundancy equals 2SLS redundancy (robust)", {
  # Stata's e(redstat) is byte-identical across estimators given the VCE (verified in the retired card fixtures), so no gmm2s fixture cell exists for this family — this identity is asserted directly instead.
  fit_2sls <- ivreg2(gril_formula, data = griliches, vcov = "robust",
                     redundant = "mrt")
  fit_gmm2s <- ivreg2(gril_formula, data = griliches, vcov = "robust",
                      redundant = "mrt", method = "gmm2s")
  expect_equal(fit_gmm2s$diagnostics$redundancy$stat,
               fit_2sls$diagnostics$redundancy$stat)
  expect_equal(fit_gmm2s$diagnostics$redundancy$p,
               fit_2sls$diagnostics$redundancy$p)
  expect_identical(fit_gmm2s$diagnostics$redundancy$df,
                   fit_2sls$diagnostics$redundancy$df)
})

test_that("testing all excluded instruments makes redundancy coincide with underid (K1=1)", {
  # griliches has K1=1 endogenous (iq); testing both excluded instruments (age, mrt) makes the redundancy LM (sum of squared canonical correlations) coincide with the underid LM (min), since there is only one canonical correlation to sum/min over.
  fit <- ivreg2(gril_formula, data = griliches, redundant = c("age", "mrt"))
  expect_equal(fit$diagnostics$redundancy$stat, fit$diagnostics$underid$stat)
})


# ============================================================================
# mroz: noconstant, K2 = 0, ALL excluded instruments tested
# F5 regression: the redundancy test partials out [X2, Z_maintained], which
# is empty here — exercises the empty-X2 guard in .partial_fwl().
# ============================================================================

test_that("redundant(all instruments) with noconstant K2=0 matches Stata — IID", {
  fixture_file <- fixture_path("mroz_nocons_redundancy_iid.csv")
  skip_if(!file.exists(fixture_file), "fixture not found")

  fit <- ivreg2(lwage ~ 0 | educ | age + kidslt6 + kidsge6, data = mroz,
                redundant = c("age", "kidslt6", "kidsge6"))
  fixture <- read_diagnostics(fixture_file)
  compare_redundancy(fit, fixture)

  # K1 = 1 with every instrument tested: the redundancy LM (sum of squared canonical correlations) and the underid LM (min) coincide.
  expect_equal(fit$diagnostics$redundancy$stat,
               fit$diagnostics$underid$stat)
})

test_that("redundant(all instruments) with noconstant K2=0 matches Stata — robust", {
  fixture_file <- fixture_path("mroz_nocons_redundancy_robust.csv")
  skip_if(!file.exists(fixture_file), "fixture not found")

  fit <- ivreg2(lwage ~ 0 | educ | age + kidslt6 + kidsge6, data = mroz,
                redundant = c("age", "kidslt6", "kidsge6"), vcov = "robust")
  fixture <- read_diagnostics(fixture_file)
  compare_redundancy(fit, fixture)
})
