# ============================================================================
# Tests: time-series operators l() / d() (Ticket F4, decision D8)
#
# Part 1: pure-R property tests (lag semantics, gaps, panels, errors,
#         option canonicalization, predict, collinearity).
# Part 2: Stata fixture comparisons — the 9 help-file examples that use ts
#         operators (help-file-specs.md H72-H76, H83-H85, H88), generated by
#         generate-ts-operator-fixtures.do.
# ============================================================================

data(phillips)

klein_path <- fixture_path("tsop_klein_data.csv")
have_klein <- file.exists(klein_path)
if (have_klein) {
  klein <- read.csv(klein_path)
}

ab_path <- fixture_path("tsop_ab_data.csv")
have_ab <- file.exists(ab_path)
if (have_ab) {
  abdata <- read.csv(ab_path)
}

# Translate Stata ts-operator coefficient names to canonical R term labels:
# "L.profits" -> "l(profits, 1)", "D2.w" -> "d(w, 2)", "_cons" -> "(Intercept)"
ts_translate_names <- function(x) {
  out <- character(length(x))
  for (i in seq_along(x)) {
    s <- x[i]
    if (s == "_cons") {
      out[i] <- "(Intercept)"
      next
    }
    m <- regexec("^([LDld])([0-9]*)\\.(.+)$", s)
    parts <- regmatches(s, m)[[1L]]
    if (length(parts) == 0L) {
      out[i] <- s
      next
    }
    op <- if (toupper(parts[2L]) == "L") "l" else "d"
    k <- if (parts[3L] == "") 1L else as.integer(parts[3L])
    out[i] <- paste0(op, "(", parts[4L], ", ", k, ")")
  }
  out
}

# Compare coefficients and SEs against a Stata coef fixture, matching by
# translated term name.
expect_coef_fixture <- function(fit, coef_file, tol_coef = stata_tol$coef,
                                tol_se = stata_tol$se) {
  fx <- read.csv(fixture_path(coef_file))
  fx$term_r <- ts_translate_names(fx$term)
  b <- coef(fit)
  se <- sqrt(diag(vcov(fit)))
  expect_setequal(fx$term_r, names(b))
  for (i in seq_len(nrow(fx))) {
    nm <- fx$term_r[i]
    expect_equal(unname(b[nm]), fx$estimate[i], tolerance = tol_coef,
                 info = paste(coef_file, "coef", nm))
    expect_equal(unname(se[nm]), fx$std_error[i], tolerance = tol_se,
                 info = paste(coef_file, "se", nm))
  }
}

# Compare the full VCV against a Stata vcov fixture, matching by name.
expect_vcov_fixture <- function(fit, vcov_file, tol = stata_tol$vcov) {
  fx <- read.csv(fixture_path(vcov_file))
  stata_terms <- ts_translate_names(fx$term)
  V_s <- as.matrix(fx[, grep("^vcov_", names(fx)), drop = FALSE])
  dimnames(V_s) <- list(stata_terms, stata_terms)
  V_r <- vcov(fit)
  expect_setequal(rownames(V_r), stata_terms)
  perm <- match(rownames(V_r), stata_terms)
  expect_vcov_match(V_r, V_s[perm, perm], tol = tol, label = vcov_file)
}


# ============================================================================
# 1. Lag semantics (pure R)
# ============================================================================

test_that("l() equals a manual lag on consecutive time-series data", {
  manual <- phillips
  manual$unem_l1 <- c(NA, head(manual$unem, -1))
  fit_op <- ivreg2(cinf ~ 1 | unem | l(unem, 1), data = phillips,
                   tvar = "year")
  fit_manual <- ivreg2(cinf ~ 1 | unem | unem_l1, data = manual)
  expect_equal(unname(coef(fit_op)), unname(coef(fit_manual)))
  expect_equal(nobs(fit_op), nobs(fit_manual))
  expect_equal(nobs(fit_op), nrow(phillips) - 1L)
})

test_that("l() lags by time value, not row position (shuffled rows)", {
  shuffled <- phillips[sample(nrow(phillips)), ]
  fit_orig <- ivreg2(cinf ~ l(unem, 2), data = phillips, tvar = "year")
  fit_shuf <- ivreg2(cinf ~ l(unem, 2), data = shuffled, tvar = "year")
  expect_equal(coef(fit_orig), coef(fit_shuf))
  expect_equal(vcov(fit_orig), vcov(fit_shuf))
})

test_that("lag ranges expand to one term per lag with canonical names", {
  fit <- ivreg2(cinf ~ 1 | unem | l(unem, 1:3), data = phillips,
                tvar = "year")
  expect_identical(fit$instruments,
                   c("l(unem, 1)", "l(unem, 2)", "l(unem, 3)"))
  expect_equal(nobs(fit), nrow(phillips) - 3L)
})

test_that("l(x, 0) is x itself and triggers collinearity handling", {
  expect_warning(
    fit <- ivreg2(cinf ~ unem + l(unem, 0), data = phillips, tvar = "year"),
    "collinear"
  )
  expect_equal(length(coef(fit)), 2L)
})

test_that("d() is the iterated (Stata) difference, not fixest's distance-k", {
  ph <- phillips
  ph$d2_unem <- c(NA, NA, diff(diff(ph$unem)))
  fit_op <- ivreg2(cinf ~ d(unem, 2), data = ph, tvar = "year")
  fit_manual <- ivreg2(cinf ~ d2_unem, data = ph)
  expect_equal(unname(coef(fit_op)), unname(coef(fit_manual)))
  expect_equal(nobs(fit_op), nrow(ph) - 2L)
})

test_that("d() ranges expand like l() ranges", {
  fit <- ivreg2(cinf ~ d(unem, 1:2), data = phillips, tvar = "year")
  expect_true(all(c("d(unem, 1)", "d(unem, 2)") %in% names(coef(fit))))
})

test_that("operators work on expressions, and inside other functions", {
  ph <- phillips
  ph$exp_unem <- exp(ph$unem)
  fit_expr <- ivreg2(cinf ~ l(log(exp_unem), 1), data = ph, tvar = "year")
  fit_wrap <- ivreg2(cinf ~ log(exp(l(unem, 1))), data = ph, tvar = "year")
  fit_ref <- ivreg2(cinf ~ 1 + lag_ref,
                    data = transform(ph, lag_ref = c(NA, head(unem, -1))))
  expect_equal(unname(coef(fit_expr)), unname(coef(fit_ref)))
  expect_equal(unname(coef(fit_wrap)), unname(coef(fit_ref)))
})


# ============================================================================
# 2. Gaps and panels (pure R)
# ============================================================================

test_that("a gap in the time variable makes the lag NA and shrinks the sample", {
  gapped <- phillips[phillips$year != 1970, ]
  expect_warning(
    fit <- ivreg2(cinf ~ l(unem, 1), data = gapped, tvar = "year"),
    "gap"
  )
  # 48 physical rows; 1948 has no lag, and 1971 loses its lag to the gap
  expect_equal(nobs(fit), nrow(gapped) - 2L)
})

test_that("panel lags never cross unit boundaries and ignore row order", {
  set.seed(42)
  pd <- expand.grid(id = 1:3, t = 1:10)
  pd$x <- rnorm(30)
  pd$y <- pd$x + rnorm(30)
  pd <- pd[sample(nrow(pd)), ]
  fit <- ivreg2(y ~ l(x, 1), data = pd, tvar = "t", ivar = "id")
  expect_equal(nobs(fit), 27L)  # first period per unit dropped

  pd_sorted <- pd[order(pd$id, pd$t), ]
  pd_sorted$xl <- ave(pd_sorted$x, pd_sorted$id,
                      FUN = function(v) c(NA, head(v, -1)))
  fit_manual <- ivreg2(y ~ xl, data = pd_sorted)
  expect_equal(sort(unname(coef(fit))), sort(unname(coef(fit_manual))))
})

test_that("subset is applied after lag computation (Stata's if semantics)", {
  # Lags must come from the full data, including rows excluded by subset
  fit_sub <- ivreg2(cinf ~ l(unem, 1), data = phillips, tvar = "year",
                    subset = year >= 1960)
  ph <- phillips
  ph$unem_l1 <- c(NA, head(ph$unem, -1))
  fit_ref <- ivreg2(cinf ~ unem_l1, data = ph, subset = year >= 1960)
  expect_equal(unname(coef(fit_sub)), unname(coef(fit_ref)))
  # 1960 keeps its lag (1959 exists in the full data)
  expect_equal(nobs(fit_sub), sum(phillips$year >= 1960))
})


# ============================================================================
# 3. Validation errors (pure R)
# ============================================================================

test_that("operators without tvar error informatively", {
  expect_error(
    ivreg2(cinf ~ l(unem, 1), data = phillips),
    "require `tvar`"
  )
})

test_that("exported stubs error outside an ivreg2 formula", {
  expect_error(l(1:5), "inside an ivreg2\\(\\) formula")
  expect_error(d(1:5), "inside an ivreg2\\(\\) formula")
})

test_that("leads, non-integer and non-constant orders error", {
  expect_error(
    ivreg2(cinf ~ l(unem, -1), data = phillips, tvar = "year"),
    "leads"
  )
  expect_error(
    ivreg2(cinf ~ l(unem, 1.5), data = phillips, tvar = "year"),
    "integer-valued"
  )
  expect_error(
    ivreg2(cinf ~ l(unem, unem), data = phillips, tvar = "year"),
    "constant"
  )
})

test_that("nested operators and non-top-level ranges error", {
  expect_error(
    ivreg2(cinf ~ l(d(unem, 1), 1), data = phillips, tvar = "year"),
    "[Nn]ested"
  )
  expect_error(
    ivreg2(cinf ~ log(l(unem, 1:3)), data = phillips, tvar = "year"),
    "top-level"
  )
})

test_that("repeated and missing time values error", {
  dup <- rbind(phillips, phillips[1, ])
  expect_error(
    ivreg2(cinf ~ l(unem, 1), data = dup, tvar = "year"),
    "repeated time values"
  )
  ph_na <- phillips
  ph_na$year[3] <- NA
  expect_error(
    ivreg2(cinf ~ l(unem, 1), data = ph_na, tvar = "year"),
    "contains NA"
  )
  set.seed(1)
  pd <- expand.grid(id = 1:2, t = 1:5)
  pd$x <- rnorm(10)
  pd$y <- rnorm(10)
  pd2 <- rbind(pd, pd[1, ])
  expect_error(
    ivreg2(y ~ l(x, 1), data = pd2, tvar = "t", ivar = "id"),
    "within panel"
  )
})

test_that("the same operator term in two formula parts is a duplicate", {
  expect_error(
    ivreg2(cinf ~ l(unem, 1) | unem | l(unem, 1) + l(unem, 2),
           data = phillips, tvar = "year"),
    "multiple formula parts"
  )
})

test_that("a variable and its lag may appear in different parts", {
  # unem endogenous, l(unem, k) instruments — the H83 pattern
  expect_silent(
    ivreg2(cinf ~ 1 | unem | l(unem, 1:3), data = phillips, tvar = "year")
  )
})

test_that("partial cannot be combined with tvar/ivar as model variables", {
  ph <- phillips
  ph$trend <- ph$year
  expect_error(
    ivreg2(cinf ~ year + l(unem, 1), data = ph, tvar = "year",
           partial = "year"),
    "time variable"
  )
})


# ============================================================================
# 4. Options referencing operator terms (pure R)
# ============================================================================

test_that("orthog accepts operator names, with whitespace-insensitive matching", {
  fit_a <- ivreg2(cinf ~ 1 | unem | l(unem, 1:3), data = phillips,
                  tvar = "year", vcov = "robust", orthog = "l(unem, 1)")
  fit_b <- ivreg2(cinf ~ 1 | unem | l(unem, 1:3), data = phillips,
                  tvar = "year", vcov = "robust", orthog = "l(unem,1)")
  expect_equal(fit_a$diagnostics$orthog$stat, fit_b$diagnostics$orthog$stat)
  expect_equal(fit_a$diagnostics$orthog$df, 1L)
})

test_that("orthog expands operator ranges like the formula does", {
  fit_range <- ivreg2(cinf ~ 1 | unem | l(unem, 1:3), data = phillips,
                      tvar = "year", vcov = "robust",
                      orthog = "l(unem, 1:2)")
  fit_pair <- ivreg2(cinf ~ 1 | unem | l(unem, 1:3), data = phillips,
                     tvar = "year", vcov = "robust",
                     orthog = c("l(unem, 1)", "l(unem, 2)"))
  expect_equal(fit_range$diagnostics$orthog$stat,
               fit_pair$diagnostics$orthog$stat)
  expect_equal(fit_range$diagnostics$orthog$df, 2L)
})

test_that("redundant accepts operator names", {
  fit <- ivreg2(cinf ~ 1 | unem | l(unem, 1:3), data = phillips,
                tvar = "year", redundant = "l(unem, 3)")
  expect_false(is.null(fit$diagnostics$redundancy))
  expect_equal(fit$diagnostics$redundancy$df, 1L)
})

test_that("invalid operator names in options are still caught", {
  expect_error(
    ivreg2(cinf ~ 1 | unem | l(unem, 1:3), data = phillips,
           tvar = "year", orthog = "l(unem, 4)"),
    "l\\(unem, 4\\)"
  )
})


# ============================================================================
# 5. predict() with ts operators (pure R)
# ============================================================================

test_that("predict on the estimation data reproduces fitted values", {
  fit <- ivreg2(cinf ~ l(unem, 1), data = phillips, tvar = "year")
  p <- predict(fit, newdata = phillips)
  # First row has no lag within newdata -> NA; rest match fitted
  expect_true(is.na(p[1]))
  expect_equal(unname(p[-1]), unname(fitted(fit)))
})

test_that("predict without history yields NA, with history yields values", {
  fit <- ivreg2(cinf ~ l(unem, 1), data = phillips, tvar = "year")
  p_no_hist <- predict(fit, newdata = phillips[c(1, 30), ])
  expect_true(all(is.na(p_no_hist)))
  p_hist <- predict(fit, newdata = phillips[29:30, ])
  expect_true(is.na(p_hist[1]))
  expect_false(is.na(p_hist[2]))
  full <- predict(fit, newdata = phillips)
  expect_equal(p_hist[2], full[30])
})

test_that("predict validates the ts context in newdata", {
  fit <- ivreg2(cinf ~ l(unem, 1), data = phillips, tvar = "year")
  nd <- phillips
  names(nd)[names(nd) == "year"] <- "yr"
  expect_error(predict(fit, newdata = nd), "not found in newdata")
})


# ============================================================================
# 6. Stata fixtures: phillips H83-H85
# ============================================================================

test_that("H83: AC IV with l(1/3).unem instruments matches Stata", {
  skip_if(!file.exists(fixture_path("tsop_phil_coef_ac_bw3.csv")),
          "ts-operator fixtures not found")
  fit <- ivreg2(cinf ~ 1 | unem | l(unem, 1:3), data = phillips,
                tvar = "year", vcov = "AC", kernel = "bartlett", bw = 3)
  expect_coef_fixture(fit, "tsop_phil_coef_ac_bw3.csv")
  expect_vcov_fixture(fit, "tsop_phil_vcov_ac_bw3.csv")
  dx <- read_diagnostics(fixture_path("tsop_phil_diagnostics_ac_bw3.csv"))
  expect_equal(nobs(fit), dx$N)
  expect_equal(fit$diagnostics$overid$stat, dx$j, tolerance = stata_tol$stat)
  expect_equal(fit$diagnostics$underid$stat, dx$idstat,
               tolerance = stata_tol$stat)
})

test_that("H84: GMM2S + AC Tukey-Hanning matches Stata", {
  skip_if(!file.exists(fixture_path("tsop_phil_coef_gmm2s_thann.csv")),
          "ts-operator fixtures not found")
  fit <- ivreg2(cinf ~ 1 | unem | l(unem, 1:3), data = phillips,
                tvar = "year", vcov = "AC", kernel = "thann", bw = 3,
                method = "gmm2s")
  expect_coef_fixture(fit, "tsop_phil_coef_gmm2s_thann.csv")
  expect_vcov_fixture(fit, "tsop_phil_vcov_gmm2s_thann.csv")
  dx <- read_diagnostics(fixture_path("tsop_phil_diagnostics_gmm2s_thann.csv"))
  expect_equal(nobs(fit), dx$N)
  expect_equal(fit$diagnostics$overid$stat, dx$j, tolerance = stata_tol$stat)
})

test_that("H85: GMM2S + HAC QS + orthog(l1.unem) matches Stata", {
  skip_if(!file.exists(fixture_path("tsop_phil_coef_gmm2s_qs_orthog.csv")),
          "ts-operator fixtures not found")
  fit <- ivreg2(cinf ~ 1 | unem | l(unem, 1:3), data = phillips,
                tvar = "year", vcov = "HAC", kernel = "qs", bw = 3,
                method = "gmm2s", orthog = "l(unem, 1)")
  expect_coef_fixture(fit, "tsop_phil_coef_gmm2s_qs_orthog.csv")
  expect_vcov_fixture(fit, "tsop_phil_vcov_gmm2s_qs_orthog.csv")
  dx <- read_diagnostics(
    fixture_path("tsop_phil_diagnostics_gmm2s_qs_orthog.csv"))
  expect_equal(nobs(fit), dx$N)
  expect_equal(fit$diagnostics$overid$stat, dx$j, tolerance = stata_tol$stat)
  expect_equal(fit$diagnostics$orthog$stat, dx$cstat,
               tolerance = stata_tol$stat)
  expect_equal(fit$diagnostics$orthog$p, dx$cstatp, tolerance = stata_tol$pval)
  expect_equal(fit$diagnostics$orthog$df, dx$cstatdf)
})


# ============================================================================
# 7. Stata fixtures: Klein H72-H76 (LIML family with L.profits / L.totinc)
# ============================================================================

klein_formula <- consump ~ l(profits, 1) | profits + wagetot |
  govt + taxnetx + year + wagegovt + capital1 + l(totinc, 1)

test_that("H72: Klein LIML matches Stata", {
  skip_if(!have_klein, "klein fixture data not found")
  fit <- ivreg2(klein_formula, data = klein, tvar = "yr", method = "liml")
  expect_coef_fixture(fit, "tsop_klein_coef_liml.csv")
  expect_vcov_fixture(fit, "tsop_klein_vcov_liml.csv")
  dx <- read_diagnostics(fixture_path("tsop_klein_diagnostics_liml.csv"))
  expect_equal(nobs(fit), dx$N)
  expect_equal(fit$lambda, dx$lambda, tolerance = stata_tol$stat)
  expect_equal(fit$kclass_value, dx$kclass, tolerance = stata_tol$stat)
  expect_equal(fit$diagnostics$anderson_rubin_overid$lr_stat, dx$arubin,
               tolerance = stata_tol$stat)
})

test_that("H73: Klein LIML + COVIV matches Stata", {
  skip_if(!have_klein, "klein fixture data not found")
  fit <- ivreg2(klein_formula, data = klein, tvar = "yr", method = "liml",
                coviv = TRUE)
  expect_coef_fixture(fit, "tsop_klein_coef_liml_coviv.csv")
  expect_vcov_fixture(fit, "tsop_klein_vcov_liml_coviv.csv")
})

test_that("H74: Klein CUE equals Stata (and LIML, the help-file demo)", {
  skip_if(!have_klein, "klein fixture data not found")
  fit_cue <- ivreg2(klein_formula, data = klein, tvar = "yr", method = "cue")
  expect_coef_fixture(fit_cue, "tsop_klein_coef_cue.csv",
                      tol_coef = 1e-4, tol_se = 1e-4)
  # The help file's point: CUE = LIML under iid + independence
  fit_liml <- ivreg2(klein_formula, data = klein, tvar = "yr",
                     method = "liml")
  expect_equal(unname(coef(fit_cue)), unname(coef(fit_liml)),
               tolerance = 1e-4)
})

test_that("H75: Klein Fuller(1) matches Stata", {
  skip_if(!have_klein, "klein fixture data not found")
  fit <- ivreg2(klein_formula, data = klein, tvar = "yr", method = "liml",
                fuller = 1)
  expect_coef_fixture(fit, "tsop_klein_coef_fuller1.csv")
  expect_vcov_fixture(fit, "tsop_klein_vcov_fuller1.csv")
  dx <- read_diagnostics(fixture_path("tsop_klein_diagnostics_fuller1.csv"))
  expect_equal(fit$kclass_value, dx$kclass, tolerance = stata_tol$stat)
})

test_that("H76: Klein kclass(1.19) matches Stata", {
  skip_if(!have_klein, "klein fixture data not found")
  fit <- ivreg2(klein_formula, data = klein, tvar = "yr", method = "kclass",
                kclass = 1.19)
  expect_coef_fixture(fit, "tsop_klein_coef_kclass119.csv")
  expect_vcov_fixture(fit, "tsop_klein_vcov_kclass119.csv")
})


# ============================================================================
# 8. Stata fixture: abdata H88 (panel differences as instruments)
# ============================================================================

test_that("H88: GMM2S + cluster(id) with d./d2. instruments matches Stata", {
  skip_if(!have_ab, "abdata fixture data not found")
  fit <- ivreg2(n ~ 1 | w + k + ys |
                  d(w, 1) + d(k, 1) + d(ys, 1) +
                  d(w, 2) + d(k, 2) + d(ys, 2),
                data = abdata, tvar = "year", ivar = "id",
                method = "gmm2s", clusters = ~id)
  expect_coef_fixture(fit, "tsop_ab_coef_gmm2s_cl.csv")
  expect_vcov_fixture(fit, "tsop_ab_vcov_gmm2s_cl.csv")
  dx <- read_diagnostics(fixture_path("tsop_ab_diagnostics_gmm2s_cl.csv"))
  expect_equal(nobs(fit), dx$N)
  expect_equal(fit$n_clusters, dx$N_clust)
  expect_equal(fit$diagnostics$overid$stat, dx$j, tolerance = stata_tol$stat)
  expect_equal(fit$diagnostics$underid$stat, dx$idstat,
               tolerance = stata_tol$stat)
})

test_that("H88 sample: differences shrink the panel exactly as in Stata", {
  skip_if(!have_ab, "abdata fixture data not found")
  # d2 needs two consecutive prior periods within the unit
  fit <- ivreg2(n ~ d(w, 2), data = abdata, tvar = "year", ivar = "id")
  ab_sorted <- abdata[order(abdata$id, abdata$year), ]
  ab_sorted$d2w <- ave(ab_sorted$w, ab_sorted$id,
                       FUN = function(v) c(NA, NA, diff(diff(v))))
  fit_manual <- ivreg2(n ~ d2w, data = ab_sorted)
  expect_equal(nobs(fit), nobs(fit_manual))
  expect_equal(sort(unname(coef(fit))), sort(unname(coef(fit_manual))))
})


# ============================================================================
# 9. Broom / S3 integration
# ============================================================================

test_that("tidy() and glance() carry operator term labels", {
  fit <- ivreg2(cinf ~ 1 | unem | l(unem, 1:3), data = phillips,
                tvar = "year")
  td <- tidy(fit)
  expect_true("unem" %in% td$term)
  gl <- glance(fit)
  expect_equal(gl$nobs, nrow(phillips) - 3L)
})

test_that("update() refits a ts-operator model", {
  fit <- ivreg2(cinf ~ l(unem, 1), data = phillips, tvar = "year")
  fit2 <- update(fit, cinf ~ l(unem, 2))
  expect_equal(nobs(fit2), nrow(phillips) - 2L)
  expect_true("l(unem, 2)" %in% names(coef(fit2)))
})
